//  Created by YIM on 26/04/2023.
#include <iostream>
using namespace std;

void pic() {
    string edpic = R"(ooodddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxdddooolllccc::::;;;;;;;;;;:::::ccccccccccccccc::::;;;,,,,'''''''''',,,,;;;;;::::::cccc:::::::;;;;;,,,''''.................................''',,,;
oooddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkxkkkkkkkkkkkkkkkkkxxxxxxxxxxxdddooollllcccc::::::;;;::::cccccclllllllllllccccc:::;;;,,,,,,,,,,,,,,,;;;::::ccccccccccccccc:::::;;;,,,,'''.........              .........''',,,
ooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkxxxxkkkkkkxxxxxkkkkkxxxxxxxxxxxdddooolllllcccc::::::::::cccclllllllllllolllllcccc:::;;;,,,,,,,,,,,,;;;::::cccclllllllllllcccccc::::;;;;,,'''........              .........''',,
ooodddddddddddxdddddddddddddddddddddddddddddddxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkxxkkkkkkkkkkkxkkkkkkxxkxxxxxxxdddoooolllllccccccc::::ccccclllllloooooooolllllccc:::;;;,,,,,,,,,,,;;;;:::cccllllllllllllllllcccccc::::;;,,,'''.......             ........''',,,
ooodddddddddddxxxxdddddddddddddddddddddddddddddxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxxkkkkxxxxxxxxxxdddoooolllllcccccccccccccclllllllooooollllllllcccc::;;;;,,,,,,,,,,,;;;::::ccclllllloooolllllllllcccc::::;;,,,'''.......          .........'',,,;;
ooodddddddddddxxxxddddddddddddddddddddddddddddxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkxxxkkkkkkkkkkkkkkkxkkkkkkkkkkxxxxxxddddoooollllccccccccccccccllllllllllllllllllcccc:::;;;;,,,,,,,,,,,,,;;;::::ccccllllllooooooollllllccccc:::;;,,,'''......        ........''',,;;;;
ooodddddddddddxxxxdddddddddddddddddddddddddddxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddddooooollllllllcccccccclllllllllllllllllcccc::::;;;,,,,,,,,,',,,,,,,;;;::::ccccllllllllloooollllllcccc:::;;;,,'''.......    ........''',,;;;:::
ooodddddddddddxxdddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkxxxkkkkkkkkkkkkkkkkkkkkkxxxxxxdddddooolllllllccccccccccclllllllllllllccccc::::;;;,,,,''''''''''',,,,,;;;;:::ccccclllllllllllolllllllccc:::;;;,,''..................'',,,;;::::c
oooddddddddddddddxxddddddddddddddddddddddddddxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkxxxxxxxxkkkkkkkkkkkkkkkxxxxxxddddddoollllllllllccccccllllllllllcccccccc::::;;;,,,,''''''''''''''',,,,;;;;;::::cccccclllllllllllllllcccc:::;;,,,''...............''',,,;;:::ccc
oooddddddddddxxxxxxddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxddddddddddddddddddxxxxxdddddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkxxkkkkkkxxxxxxxxxxxxxddxxxxddddddollllllllllllllllllccccc:::::;;;;,,,''''............''''',,,,;;;;:::::cccccccllllllllllllcccc:::;;,,'''.............''',,,;;:::cccc
oooddddddddddxxxxxxddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkxxxxxxkkkkkkkkOOOOOOOOO00000000000OOOOOkkxddolllccccccccc::::;;;;,,,,''''..................'''',,,,;;;;::::::cccccccllllllllccccc::;;;,,''.............'',,;;;:::ccccc
oooddddddddddxxxxxxdddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOO000000000000KKKK000000000000000000OOkxxdolc::::;;;;,,''''''......................''''',,,,;;;;;:::::ccccccllllllcccccc::;;,,,''...........'',,,;;:::cccccc
ooodddddddddddxddxdddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxddxxxxxxxxxxxxxddddddddxxxxxxxxxxxxxxxxxxkkkkkkxkkkkkkkxxkkkkkkkOOOOO00000000000000KK0000KK0000000000000KKKKKKKKKKKK0Okdolc;,,'.................................''''',,,,;;;;:::::cccccllllcccccc:::;;,,'''.........'',,,;;;::ccccccc
oooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkxxkkkkkOOOOOOOO0000000KKKKKKKK000000000000000000000KKKKKKKKKKKKKKKXXKK0kxdl:,'..................................''''',,,;;;;::::cccccllcccccc:::;;,,,'''......''',,,;;:::cccccccc
ooooddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxddddddddddddddddxxxxxxxxxxxkkkxxxxxxxxkkkkkkkkOOOOOO000000000000000000000000000000000KKKKKXXXXXXXXXXXXXXXXXXXXXXXK00Oxl:,..........       .................'''',,;;;;:::ccccccccccccc::;;;,,'''''''''''',,;;;::ccccccccc
ooooddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddxxdxxxxxxxxkxxxxxxxkkkkkkkkkkOOOOOO00000000000000000000000000KKKKKKKKXXXXXNNNNNWWNNNNNNNNNNNNNNNXXXXXXXK0kdc'.  ..            ................'',,,;;::::cccccccccccc:::;;,,,''''''''',,,;;;:::ccccccccc
ooooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddooddxxxxxxxddxxxxxxxxxxxkkkkxkkkkkkOOOOOOOOOOO0000000000000000KKK00KKKKKKKXXXXNNNNNNNWWWWWWWWWWWWWWWWWWWWNNXXXXXXXXK0xl;..  ......            .........'',,;;;:::ccccccccccc::::;;,,,,''''''',,,,;;;::cccccccccc
ooooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddoooooooooddxxxxxdddddxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOO0000000000000KKKKKKKKXXXXXXXXNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWNNXXXXKKKXKKKko;............ ... .    ......'',,;;;;:::ccccccccccc:::;;,,,,,,,,,,,,,,;;;:::cccccccccc
ooooodddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxdddddxxxxxxxxddddooollllloooddxxxxddxxxddxxxxxxkkkkkkkkkkkkkkkkkkOOOOOOOOO00000000000KKKKKKKXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNNNNXXXKKKKKKK0ko;'.......................''',,;;;:::cccccccccccc:::;;;,,,,,,,,,,,,;;;:::cccccclllcc
ooooodddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxddxxxddxxxxxddooollccclloodxxxxxxxddooddxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOO000000KKKKKXXXXXXNNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNNXXXXKKKKKKKK0kl;'...................'',,,;;;::::cccccccccccc:::;;;,,,,,,,,,,,;;;;:::cccclllllcc
ooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxdoollcccccclloooddddddddddddddxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOO000000KKKKXXXXXXXXNXXXXXNNNNNXNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNWNNNNXXXXXXKKKKKKKKK0xl;''''''''''''''''',,,,;;;:::cccccccccccccc:::;;;;,,,,,,,,,,;;;;:::cccclllllcc
ooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxdddoolc:::::cccclloooooodddxxxxdddxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOO000000KKKKKKXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNXXXNNNXXXXXXXXXNNNNNNXXXXXXKKKKKKKKKKK0Odc;',,,,,,,,,,,,,,;;;;:::ccccccllllcccccc:::;;;;,,,,,,,,,;;;;;::cccccllllccc
oooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoolcc:;;;::::ccllloooooooodddddddddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOO0000KKKKKKKKKKXXXXXXXXXXXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK000KK0xl;,,;;;;;;;;;;;;::::cccccccllllllccccc:::;;;;,,,,,,,,,;;;;:::cccclllllccc
oooddddddddddddxddddddddddddddddddddddddddddddddddddddddddddddddddddolc:;;;,,;;;::::clllllooodddddddddddxxkkkkkkkkkkkkkkxxxxkkkkkkkkkkkOOO00000KKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKK00KK0xl:;;::::::::::cccccccccllllllllccccc:::;;;,,,,,,,,,,;;;;:::cccclllllccc
ooodddddddddddxxdddddddddddddddddddddddddddddddddddddddddddddddddddol:;;;;;;;;;;::::ccllloooooddddxxxxxxxxkkkkkkkkkkkkkkxxxxkkkkkkkkkkkOO00000KK00000KKKKKKKKKKKXXXXXXXKKKXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXXXXXXXKKKKKKKKKKKKKKKK0000000xoc::ccccccccccccccllllllllllllcccc::;;;;,,,,,,,,,;;;;;:::ccclllllllcc
ooodddddddddddxxdddddddddddddddddddddddddddddddddddddddddddddddddolc:;,,,,,;;,,,;;;::cccllollooddddxxxxxxxxkkkkkkkkkkkxxxxxxxkkkkkkkkkkO0K0000KKK00000000KKKKKKKKKKXKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK00000000kolccccclccllllllllllllllllllccc:::;;;,,,,,,,,,,;;;;:::cccclllllllcc
ooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:;,,,,,,,''',,;;;;:ccllllloooddddxxxxxxxxkkkkkkkkxxxxxddxxxxkkkkkkkkO00000000000000000000000KKKKKKKKKKXXKKKKKKKKKKKKKKKKKXXKKKXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0KK00000000kollllllllllllllllooollllllccc:::;;,,,,,,,,,,,;;;;:::ccclllllllccc
oooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:,,,,,,,''''',,,;;::ccclloodddxxxxdddxxxxxxkkkkkkxxxxxddddxxxxkkkkkkkO00000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000K0Oxollllllooooooooooolllllcccc::;;,,,,,,,,,,,,;;;;:::cccllllllllcc
ooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:;'',,'..'''''',,;;:ccclllooddddddoooodddddxkkkkkkxxxddooddxxkkkkkkkkOO0000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKKKKKKKKKKKKKKKKKK000KK0KK000Oxoooooooooooooooollllcccc::;;;,,,,,,,,,,,,;;;:::cccccllllllccc
oooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddolc;'',,''......''',;:::ccclllloollooddddddxxxxkkkxxxxxxdddddddxkkxxxxkkOOOO00000000000000000000000000K0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKKKKKKKKKKKKKKKKKKK00000000K0000Oxdoooooooooooooolllcccc::;;;,,,,'''',,,,,;;;:::cccccllllllccc
ooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddool:'.'''......''''',;::::::clcclloooooooodxxxxkkkxxxxxddddxdddddddxxxxxkOOOOOOOO00000OO000000OOO00000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXKKKKKKKKKKKKKKK00K0000000000000kdoooooooooolllllccc:::;;;,,,''''''',,,,,;;:::cccclllllllccc
oodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol,..'......''''',,;;;;;;;;:cllooollooodddxxxxxxxxxddddddddddddddxxxxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOO000000000000K0KKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXKKXKKKKKKKK000KKKK0000000000000kxoooooooollllcccc:::;;;,,'''''''''',,,,;;:::cccclllllllccc
odddddddddddddddddddddddddddddddddddddddddddddddddddddddddoddl;'........''''',,,,,,,,;::ccllllloodddddddddxxxdddddddoddddddddxxdxxxkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOO000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKXXXKKKKKK0000KKKK0000000000000OOxollollllllcccc:::;;,,,'''''''''''',,,;;:::cccclllllllccc
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddoodo:'..........'''''''''',,;:cccccloooooollooddddddddddddddxxxxddddddddxxxkkxkkkOOOOOOOOOOOOOOOOOOOOOOOO00000000000KKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKKKKXXKKKKKKKK00KKKKK0000000000OOOOOxollllcccccc::;;;;,,''''......'''',,,;;:::cccllllllllccc
ddddddddddxddddddddddddddddddddddddddddddddddddddddddddddodoc,...................'',;::::cclooooooooodddddddddddddddxxxdddddoddddxxxkxxxkkkkkOOOkkkOOOOOOOOOOOOOOOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXKKKKKXXXKKKKKKKKKKKKKKKKKKK0000000OOO0Oxolccccc::::;;;,,,'''.........''',,,;;:::ccclllllllcccc
dddddddddxxxdddddddddddddddddddddddddddddddddddddddddddoodoc,....................'',;::cclllloooolooodddddddddddoooddddddddddddddxxkkxxxkkkkkkkkkkkkOOOOOOOOOOOOOOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOOOOOOkoc:::::;;;;,,,'''............'',,,;;:::ccclllllllcccc
ddddddddxxxxxdddddddddddddddddddddddddddddddddddddddddooool;....................'',;;::ccccllllcllooodddddddoooooooddddddddddddddxxxxxxxxkxkkkkkkkkkkkkkkkkkOOOOOOOO0000OOO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXKKKKKKKKKKKKK0000KK0000OOOOOOOOxlcc:;;;;,,''''..............''',,;;:::cccllllllllccc
dddddddxxxxxxxddddddddddddddddddddddddddddddddddddddddoooc;'....................',,;;;::::ccccllloooooddddddoooooooddddddddddddxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkOOOO00000000KK00KKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKXXKKKKKKKKKKK00KKK0000OOkkOkkkOxlcc:,''''''................''',,;;:::ccclllllllcccc
ddddddxxxxxxxddddddddddddddddddddddddddddddddddddddddoool:,....................',,;;;;;;::ccccloooooodddddddooooooooddoooddddddddxxxxxxxxxxkkkxxxxkkkkkkkkkkkkkkkkOOOO0000000KK000KKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKXXKKKKKKKKKKKKKKKK00000OOOOOkkOkdc;,;'''...................''',,;;:::ccclllllllcccc
ddddddxxxxxdddddddddddddooodddddddddddddddddddddddddooool:'..................''',;;;;;;;:::cloooooooodddddddollloooooooddddddddddxxxxxxxxxxxxxxxxxxkkkkkxxkkkkkkkOOOOOO00000000000KKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKK0000KKKKKKK00000OOOOkkkOko;;:,...........   .......''',,;;::cccclllllllcccc
ddddxxxxxxddddddddddddoooooooooodddddddddddddddddddooool:,..................'',,,,,,,,;:::clllllllloooooddddoolloooooloooddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOO00000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKK0000000OOOOOkOOko:;'.........      ......'',,;;;::cccclllllllcccc
ddxxxxxxxxddddddddddooooooooooooddddddddddddddddddddoooc;.................''''''',,,;::cclllcllllloooooooddddooooooolloooddddddddddddxxxxxxxxxxxxxxkkkkkkkxxkkkkkOOOOO000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK00KK0000000OkkkkOOxc,,''......       ......'',,,;;::ccccllllllllccc
xxxxxxxxxdddddddddoooooooooooooodddddddddddddddddddddolc,.....'''......''.'''''',;;:::ccccllllllllooooooooooooooooolloooodddddddddxxxxxxxxxxxxxxxxxkkxxxxxxxxkkkkOkkOOOO0000KKKKKKKKKKKKKKKKKKKKXXXXXKKKXXXXXXXXXXXXXXXXKKXXKKKKKKKKKKKKKKKKK0000000OOOkkkkkdc;,,,......     .......'',,,;;::ccccclllllllccc
xxxxdddddddddddddooooooooooooooodddddddddddddddddddddol:,...................'''',;;:::cllccccclloooooooooooooooooooolllloooddddddxxxxdxxxxxxxxxdddxkxdddxxxxxkkkkkkkkkOOO00000KKKKKKKKKKKKKKKKKKXXXXKXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOOkkkkkxo:;;;;,'...............'',,,;;::ccccclllllllccc
dddddddddddddddddooooooooooooooooddddddddddddddddddddooc,..........'''......',,;;;::cllcccccclllooooooooooooooooooolllllloodddddddxddddxxxxxxxxdddxxxxxxxxxxxxxxkkOOOkkO00000KKKKKKKKKKKKKKKKKKKXXXXXKKXXXKKXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOkkkkkkkdc;;,,,,''.............'',,,;;:::cccllllllllccc
dddddddddddddddooooooooooooooooooddddddddddddddddddddooc,'.........'.......',,,;::::cc::::cccllllooooooooooooddooolcccclllodddddddoooddxxdxxxxxxxdxxxxxxxxkkxxxkkkkkkkO00K00000KKKKKKKKKKKKKKKKXXXXKKKKKXKKKXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOkkkkkkkkxoc:;,,,'''............'',,,;;:::cccllllllllccc
ddddddddddoooooooooooooooooooooooodddddddddddddddddddolc;,'...............',,,,;;;;;:ccccccclllloooooooooooooddddolccccclloooooddooooodxdddxxxxxddxxkkxxxxkkxxxxkkkkkOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKKKKKKKKKKKKKKK00000000OOOkkkkkkkkdlc::;,,'''...........'',,,;;:::cccllllllllccc
ddddddddoooooooooooooooooooooooooodddddddddddddddddoool:,,'............''''',,,;;;::cccccclooollllllooooodooddddddolcccccclloooooddddddxxxxxxxxxxxxkkkkxxxxxxxxxkkkkkkOO00000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKKKKK000KKKKKKKKKK000000000OOkkkxxkkkxolc::;,,,''..........''',,;;:::cccclllllllccc
ddddddoooooooooooooooooooooooooooooodddddddddddddooooll:;,''.............'',,,;;;:cllclllloooooolloooooddoodddddddoolccccccclooooddddddxxxxxxxxxxddxxxxxdddxxxxxxkkkkkkOOOO00000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKK00000KKKKKKKKKKKK00000000OOkkkkxkxxxdlccc:;,,,''........''',,,;;;::cccclllllllccc
ddddooooooooooooooooooooooooooooooooooddddddddodoooollc:,''.........''..'',,;;::cclllllllllllllooooooooooooodddddddollccccccllllooooooddddddxxxddddxxkkkxxxxxxxxkkkOOOOOO000000000KKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000KKKKKKKKKKKKKK0000000OOOkkkxkkxxdl:::::;,,,'''''....'''',,;;;:::ccclllllllccc
ooooooooooooooooooooooooooooooooooooooooooooddddooooll:;''........''''''',;;;:::cllllllccclllooooooolloodooodddddddoolcccccccllllloooodddddddxxxxxxxxxxxxxxxxxxkkkkOOOOOOO0000000000000000KKKKKKKKKKKKKKKKKK0KKKKKKKKKKKK00000000000K000KKK00000000OOOOkkkxxxxxddoc::::;,,,'''''''''''',,,;;:::cccclllllllcc
ooooooooooooooooooooooooooooooooooooooooooooooooooollc;,'.........''''',;;;:ccclcccccccclllllllolooooooodddddddddddoolccccc:cllllloddddddddddxxxxxxxxdddxxxxdxxxxxkkkOOOOOOO000000000000000000000000KKKKKKK000KKKKKK000000000000000000000000000000OOOOOkkkxxxxxddolc:;;;,,,''''..''''''',,;;;::ccccllllllllc
dddooooooooooooooooooooooooooooooooooodddooodoooooolc:;'......''..'''',::::c::ccllclllcccllcclllllooooooodddddddddddolccccccclllllloddoooddddddxxxxxxxxxxxxxxxxxxkkkkkkOOOO000OO00KK0KKKKKKKKKKK0000000000000KKKKKK00000000000000KKKKKK0000KK0000OOOOkkkkkxxxxxdddolc:;;;;,''''..''''''',,,;;:::ccclllllllll
ddddooooooooooooooooooooooooooooooooooddoooooooooooolc;'....''''....';::::::cllccccccccccllllllllllooooooddddddddxxxdolccccclllclllodddooododddxxxxxxxkkkxxkkkkkkkOOkkkOOOO000OOO000000KKKKKKKKKKKKKKKKK0KK00KKKKK0000000000KKKKK0000KK0000000000OOOOkkkkxxxxxxddoolc:;,;;;,''''.....'''',,;;;::ccccllllllll
ddddoooooooooooooooooooooooooooooooooododddoooooooollc,'''''''...'',;:;;;:cccc:::::ccclcllllccllllllooooooooddddxxxxxdollllllllllllodddooodddddddddddxxxxxxkkkkkkkOOOOOOOOOO00000000KKKKKKKKKKKKKKKKKKKKKK00000000000000000KKK0000KKKKKKKK00000000OOkkkkkxxxxxxxdlccc:;,,,;,''''......''',,,;;:::cccclllllll
ddddddooooooooooooooooooooooooooooooooddddoooodddoolc;,''''''...',;:::;;clccc:ccllllooollllcccllllllooooooodddddxxxxxddolooollllllllooooodddddddxdddddddddxxkkxxkkkOOOOOOOO0000000KKKKKKKKKKKKKKKKKKKKKKKKK00KKK0000000OO00000000000KKKKKKKKK0000OOkkkkkxxxxxxxxdlc::::,,,,,'''.........'',,;;;:::ccccllllll
dddddddddoooooodddooooooooooodddddddddddddddoddddooc;,'''.....',;:c:;;;ccc::cc:cclllccclllcccclllllloooooooddddddddddddooooolllllllooodddddddddxxddddxxxxxxxkkxxkkkkkOOOO0000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000KKKK000OOOOOOkkkxxxxxxddoc;;::;,,,,,'..........''',,;;:::ccccllllll
dddddddooooooooddoooooooooooddddddddddddddddddddddl:,'.''....,:::::;;:cc:::::;:cccc::::c::cccccllcclloooooodddddddooooooooooollllllloddoooddddddddddxxkkkxxxkkkkkkkkkkkkkOOO0000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000K0000000000OOOOOOOOOOkkxxxxxxddoc;;::;,,',,'...........'',,,;;:::cccllllll
dddoooooooooooooooooooddoodddddddddddddddddddddoolc;'.......';;;:::::cc:;:::::clc:::ccc::::ccccllccllooooooooodddoooddoolooooooooolloooolooodddodddddxxxdddxxxxxxxkkkkkkOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKK00KKK00000OOOOkkkOOkkxxxxxxxdoc:;;::,,''''............'',,,;;;::ccccllll
ooooooooooooooooooooooddoodddddddddddddddddddddoodol:'......,;;:c;,:ccc:;:::clcc::::::c::::ccccclllllooooooooddddoooddoollloooooooooooooooooooooooodddddxxxxxkkxxxxkkkkOOO00000KKKKKKKKKKKKKK0000KKKKKKKKKKKKK0000KKKK000000000KKKK0000000000000OOkkkkkkxxxxxxxxdoc:;;:;,''''..............'',,,;;;:::ccclll
oooooooooooooooooooooooooodddddddddddddddddollllodxkkxl;'..',,;::,';::;,,;;:cccc::;;:::::::::ccllccclooolooooddddoooddooooooooooloooooooodooooodddooddxxxxxxxkkkkkxkkkkOO0000000KKKKKKKKKKKKKKK00000000KKKKKKKKKKKKKKK0000000000KK0000000000000OOOOOOOkkxxxxkkxxdoc:;;:;,...................''',,;;;:::ccccl
oooooooooooooooooooooooooooddddddddddddddolccccccclodxxdc;'',,,;;'';::;,,;;:cc:::::::c::::::::clllcclloollooddddoooooooooooooooollloooddddddooddddooodddddxxxxxkkkkkkkkkO0000000KKKK000KKKKKKKKKKKKKK00K00000KKKKKKKKKKKKKKKKKKKKKKKKKK000000OOOOOOOOkkkkxxxxxxxddl;,;;;,.........    ........'',,,;;;:::ccc
ooooooooooooooooooooooooooooooddddddddddlc;;,,,;;:cclooool:,,,',;,';::;;;;;;:cc::c::::::::::::cccllcllloooooodddddoooooooooooooooooddddddxxxxxddddddddddooddxxxkkkkkkOOOOO000000KKKKK0KKKKKKKKKKKKKKKKKKKKKKK0KK0000KKKKKKKKKKKK00KKKKKKKK0K0O00OOOOkkkkkxxxxxxdddl;,,;;'.''......     ........''',,;;;;:::c
ooollooolllloooooooooooooooooooodddddddl:,........',:clllcc:;;;;;'';:;,',,,;::::::;;::::::::ccccclllooollooooodddooooddoooooooooooodddxddddxxxddddxddddddoooddxxxxxkkkkOOO000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKK000OOOOOOOO00000000KKKKKKKKKKKK0000OOOkkkkkxxxxxxxdddoc;,,,'........       .........''',,,;;;;:
llllllllllllllllllllooooooooooooooodddo:;'...........,:::::::::;;,,;;;''',,,;;;::;;;;;::::::ccclllcllllllooolloddooooooooooooddoooodddddddddddxxxxxxdddddddddddxxxxxxxxkkkkOOOOOO0KKKKKKKKXKKKKKKKKKKKKKKKKKKKK00000OOO00000000000KKKKKKKK000000OOOkkkOkkxxxxxxddool:;,,,'''... ...     ..........'''',,,,;;
lllllllllllllllllllllllooooooooooooodol:;,............,,;;::::;;,,,;;,'',,,,,;;;;;:::;;:::::ccclllccclllloooolooddoooooooddddxxdooodddddddddddddxxxxxxxxddddxxxxxkkkkkkkkkxkkkkkkOO0KK0KKKKKKKKXXKKKKK00KKKK00K00KKKKKKKKKKKKKKKKKKKKKK0000000OOOOOkkOkkxdxxxxxddol:::;,,,''........................''',,,,;
llllllllllllllllllllllllllllooooooooolc::,........'''',,,;;:::;;;;;;,,''''',,;;;:::;;::;;;::ccccccccclllllloooooddoooollllooooooooodddddddddddddddxxxkkkkkxdddddxxxxxxxkkkkkOOOOO0000000000KKKKKKKKKK000KKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKK00000OOOkkkxkkkxxxdddoodol:;;;,,,,'........................'''',,,,
llllllllllllllllllllllllllllllooooooolcc:'.....';;,''..',;::::;;;;;,,,'...',;;::::;;;::;;;::cccccllllllllllloolodxxdddocccoooooooooddxkxxxxxddxxdddddxxxxxxxxxddddxxxxdxxxkkkkkOOO000KKKKKKKK000KKKKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000OOOkkxxkkkkxdddooddoc;,;;,,;,,'......................''''',,,
lllllllllllllllllllllllllllllllllloooc::;'....,;::;;,,,,,,,,;;;,,,,''''..',;::::::;;;;;::::::ccccllllllooolllllodxxxxxdolllodddooddxxkOOOOOOkkkOOkkkkkkkxxxkkkxxdddddxxxxxxxkkkkOkkO000KKKKKKKKKKKKKK0OOKKKKKK00KKKKKKK0000KKKKKKKKKKKKKKK00O00OOOOkkkkkkxxxddddddoc;,,,,,''''.....................''''''',,
llllllllllllllllllllllllllllllllllollc::,'',,,;::::;;;,'..',,,,;:;,''..'',,;::::::;,,;:::::ccccllllllllooollccccllooddooolloodddddddxxxxxxkkkkOOOOOOOOOOOOOOOOOkkxxxddddddddxxxkOOkOO000000KKKK0KKKKK0OOKKKKKKOOKKKKKKK0KKKKKKKKKKKKKKKKKK00OOOOkkkkkkkkxxddddddddoc:;,,''''''............'''''''''''''',,,,
llllllllllllllllllllllllllllllllllllc::;,',;;;::::::::;,...',',,;,,'..'',,,;:::;;;;;;;::ccclllllllllooloooollcccclloolooooooooodooodddddddooddxxkkkOOOOOOOOOOOOOO0OOkkkxxxdxxxxxOOkkO0000O000KK00000K0OOKKKKK0OOKK0000K000KK0KK0KKKKKKKKKK000OOOkkkkxxxxxdddddddddoc:::;,,,'''''''''''''''''',,,,,''',,,,,,,
llllllllllllllllllllllclllllllllllllccc;,,,;;::::::cclc:;,,,'''''''.'''.';;:::;;;;;::;;:cclllllolllllllllooollllcloddooooooooooollloooddxxxdddddxxkkkkkkkkOOO00OOOOOOOOOOOOOOkxxkOkO00OOOO000000O0000Oxk00KK0OO0KK0KKK0OO000000000000000OOOOOOkkOOOkxxddddddddddddocccc:;,,,,,,,,'',,,,,,,,,,,,,,,,,,,,,,,,,
llllllllllllllllllllllllllllllllllllc::;;,;;;::;;;:;:lolc;,'''..'''''''',;::;;,;::;;;:::clloooooooooooollooollllclodxxdolllooooollllcclodddddxxxxxxxkkkkxxxxxkkkkkOOOOOOOOOOkkkkOO00KK0OO0000K0OO0000OxxO00K0kk0KKKKKKOO0KKKKKKKK0000000OOOkkxxkkkkkxxddddddooodddlcccc:;;;;;;;,,,,,,,,;;;;;;;;;;;;;;;;;;;;;
llllllllllllllllllllllllllllccclllll:;:;;;;::::;;;,,,;::;,'.''..',,,,'',,;:;,;;:cc:;::::ccloooooooddddollooolllc:ccloolccclllllllccc:;;::cllllloooollllooddddddxxxxxxxxxxkkkxkkO00000000000OO000OOO00kxxkO00Oxx0KKKKK0O0KK0KK00000KK00000OOkkkkxxxxddddddddddooodoolcc:::::;:::::;;;;;;;;;;:::::::::::::;;;;
llllllllllllllllllllllllllllccclllll:::;,,;:::;;,,,'..''........''',;,,,,,,;::c:::;;;:::cccclloolooddddollloooolccclodolclllllllcccllcc:::ccccc::clllllllcccllllloodooddxxxxxxxxkkxxkkOOOOOOO00OOkkOOkddxO00kddO00000OO0K0000000000000OOOkkkkxxxkxxddoodddddddoddoolcc::::::::::::;;;;;:::::::::::::::::::::
lllllllllllllllllllllllllllllllcllllc:c:;,;::;;,,'''.....  ..''''''',,,;;,,;cc::;;,,;::ccccccllllooddddooooooooooccldddollllllcclllcc::c:::cc:::;;;;::cclolc::c::clooodddooooooddoooodxkxxkkkxxxxxkkkxodxOOOdodk0000OkO000000000000000Okkxkkkxxxxxxxxddddddddddddolclcc:::ccc:::::::::::::cccccccccccccccccc
llllllllllllllllllllllllllllllllllllc:c:;;:::;,,,,,,'..............',,;:;,;:clc:;,;;:::cccclllllloddddooddddollooolloooolcccllccccc:;;;;:;,,;;;;,,,'',,,,;ccc::;;;;:clllc:::::clooolloooolloooodxkxddxxkkkkdodkkkkkkkxkOOOO00000K00000Okkxxxkkkkxxddxxddddxddddddolclllcc:::::::::::::::cccccccccccccccccccc
llllllllllllllllllllllllllllllllllllc:::;;:::;,,,,,,'...   .......',,,,;;:clc:;,;;:::;;:cllllllloooodddooooddolc:cllolllllllcccc:;;;;,,,'..................',;;;;,,,;;:ccccc:::cccccccc:::cccodxddddxxddddolldkxddxkxodkOkkkO0O0000OOOOOkkkxddddxxddddddxxxdddoddolc:lllccc::::::::::::ccccccllllllllccccccc
llllllllllllllllllllllllllllllllllllc::;;;:ccc:,,,''...   ......,,,,,,;;:::;,'';;::;;:::cllllllllooooddddooloooolc::cccc:::cccc::;,''....    ........      .....'''''...',,;;,,,;,,,;;,,,;;;;:cllloollcloocclxkdlldxxccdkkdoxkkkkOOkxkkkkkOOkxxxxxxdxxkxxxxdddoddollccccc:::::::::::::ccccclllllllllllllllll
llllllllllllllllllllllllllllllllllllc:::;;:cllc:;,'.......','..,cc:;,,,;;;;''',,;;::;;:::cclllllllloooooddxdollodddolcccc:;;,,,;,'....................    .     ... ...    ..............''''',;::ccodxkxo::ldxdc:cdxo:coxocldxxddxxxxxkkkkkxxxkkxxxxkxxxxxdddodollllccc:::::;;:::::::ccccclllllllllllllllll
llllllllllllllllllllllllllllllllllllccc:,,:loolc:;,'';;;;;;,'',:cc:;,'',,;,,,;,,;:::;:::cccccllloooodollllooooooodxxxxdddddlcc::;,'''''',;:::;;;,..........   ......         ..................',:odddddolccclddl;,coo:;:ll::codooodxdddxxxkxxddxxxxkxxxkkxxddddlc:clccc::::;;:::::::cccccclllllllllllllllll
llllllllllllllllllllllllllllllllllllccc:,,;codoc:;;;:c:;,''..,cccc:;''',;;,,;;'';;:;;;::cclccccllllodxxdddollccccccllllllllc:;;;::::::cc;;cllllcc:;'.........''.....            .........'''',,,;ldxkOkkkxxdolodc'.';:;',;:;,;:ccllooolloooddoodddxxxxkkkkxxddxdl:::ccc::;;;;;;;:::::cccccclllllllllllllllll
lllllllllllllllllllllllllllllllllllllllc;',:lddoc::cllc;,'..':lcc::;,,,;,'',,,,;;;,,;:ccccclllllcccllooodddxxxddoooooolllloollllllloollol:cloooooolcc::::::;;;;,'...              .....,,,,',:ccllodxkOkkkkkdolc;........''...',,:clllccllllllllooodoodxxkkxddxo:;::ccc:;;;;;;;;;::::cccccllllllllllllllllll
lllllllllllllllllllllllllllllllllllllcll:'.,:cooollllllc:;,';lllc:;;,,;;,'',;,,,;;,,;:c:cc::clllllcccloooloooddddddxxxddooooooddxxddddooxdlcloooooolodddooolccc:;,,'...... ...........,:lc;,;:codxxkkxxxdddxdo:,.................,:clllllcccccc::cccclldxxxxdooc;;::cc:;;,,,,;;;;::::cccccllllllllllllllllll
lllllllllllllllllllllllllllllllllllolccol;..';:cloddoolc:::;:cllcc;,,,,,,''''',,,,;::::::c:::ccllolooooooooooddxxddxxxxxddooodkOOkkkkkdodxxoooloolllllllloooooddoollcc::::;;;,',;;'..':odocccllodxkO00OOkxddol,......            ..,;clollllllllcc::ccodxxdddol:;;;:::;,;,,,;;;;;::::cccccllllllllllllllllll
llllllllllllllllllllllllllllloolllooolclol,..,;:cloddolc:::::cllcc:,,,,,''''',,,,',;:::::::ccc:cccclooooddddddddddxxxxxxxxxxdxkOkkkkkkkxdodxxdddxxxddddddddddddxddddddxxxddooc:clc,',:oxxdllooddxkOOOOOOOOOkxl'                     ...,,;;::;;;,,,;:ccloooddol:;;;:c;;,,,,,;;;;;::::cccccllllllllllllllllll
llllllllllllllllllllllooooooooooooooolclodoc,'',;cldddol:::ccclccc:;,,,,'''''',,,',,;;;;::::cccccccllodoodxxxxxxxxkOOOkkkkkxxxxddddxxxkOOkxxxxxddxkxxxxxkkkxdddddddddddxxdxxdolllc::coxxdoloodxxkO0KKK00OOkxdc'.                         ......''',;:ccccclodoc:::cc:;,,,,,,;;;;;::::cccccllllllllllllllllll
lllllllllllllllloooooooooooooooooooooolloxxdl:;,';coddddolccccccc:;;,,'''',,''',,,;;;;;:::::cccccclooodooddxdxxddxkOOOOOOkkxxxxdddxkkxxk0OkkkkxxxxxxxxxxxxxxddddddddoodddddddollooooodxkxoooodkOO000KKKKKK0Odl;,'..                      .    ....',;:cccloddolc::cc;,,,,,,;;;;;:::::cccccllllllllllllllllll
lllllllllllloooooooooooooooooooooooooolcldxxdol:;,;clodddolc::::::;,;,,'',,,''',,;;,,;;;;::::cccclloooooodddoddoodxkkOOOOOkkkOOkxddxxooxkkkkkkkkkkxxxxxxxxxddddddoddoodddxxxdoooddxxxxxxdooooxO00KKKKKXKKK0Oxlcc:;,........   ......   .....     ...';:cccodooooc:cc:;;;;;;;;;;::::::cccccllllllllllllllllll
llllllllooooooooooooooooooooooooooooodolcldxddoolc:;;cllool:,,,;::;,,,,',,'',,'',',,;::;;::::cccccclooloodoollooddxxxxxxxkkkkkkkxxxxdoodxkxxxxxxxdddddddddoooddooooooodddxxxddxxxkkkkxxdollodxkO0KKKKKXKKKKOdlccllool:;,,,''..........',;:;..     ...,;:clodollolccc::;;;;;;::::::::ccccccllllllllllllllllll
lllloooooooooooooooooooooooooooooooodddoccldooddocc:;,,;::::;;,;;;;;,,,',,'',,,,,,,,;:;,;;;;::cc:cclllolooooolloddddddxxkkkkOO0OkkkOOxdoxkOkkkxxddooooooolllloolloddxxkkkkkxxxxkkOOkkkxddolldxkO0KKKKKKKKK0Oxooooddooolccccllc:;,',,:lodolc;,'.. ..';;;::cloolccolllccc::;;:::::::::ccccclllllllllllllllllll
lllooooooooooooooooooooooooooooooooddoddlccooodddlcccc:;::cclc:;,;;;,,,,,,',,,,,,,,',,,,,;::;:::cccccloolooollcllooddxxkkkkkkO00kxxxOOkxxdddxxkxdoooodddoooooddddxkkOOOOOkxxxxxkkO0OOkddoooodxk00KKKKKKKKK0kdddoodddddooooodxxxdddddddxxddoool:,...,:c:;;:ldol:cllolccllcc:::::::::cccccclllllllllllllllllll
ooooooooooooooooooooooooooooooooooddoodddlcclloddocclllllllloolc;,,;,,,,,,,,,,,,,,,,,,,,,,;;;;;;:cccclooooollccclloddddxxxxkkkkkkkxxkkkxxxxxdxkkkxxxxxxxxxxxxxkOOkOOOOkOOOxxdxkkkkkOOOxooooddxkO0KKKKKKKK0Okxxddodxddddooooddxxxxddoooooooooolc::,.,:llccllddoccclllcccccc:::::::::cccccclllllllllllllllllll
ooooooooooooooooooooooooooooooooodddoodddoocclooooolclloooooodol:,,,,,;,,,,,,,,,,,,,,,,,,,;;;;;;::ccclllllllclllllloddddxddxxkkOOOOkxxkkxxxxxxxkOOOkxxkkOOkkkOOOOOkkkxxkkkkkxxkOOkddkOxoooodxxkO0KKKKKKKK0Okxxxddxdoodddooooddxkkxxxdoooooolllllll:;;cooollloolcccclccc:::::::::ccccccccclllllllllllllllllll
ooooooooooooooooooooooooodddddodddooodoodddlcclloodolllooooodddl:;,,,;;;;,,,,,,,,,,,,,,,,;;,;;;;;::::ccclllllllollloddddxxxxkkkkkkOOkkOOOOkxxxxkkOOkkkOOOkkkkkkkkkkkkxxkxxxxxkOOOkdoxkdooooddxO00KKKKKKKK0Okxxxxkkxxdddddddddoodxxxxxxxddooodxxdolcccccloolllccccc:cllcc:::ccc:cccccccccclllllllllllllllllll
ooooooooooooooooddddooodddddddddddooddooooddoc:clooolclooddodddl:;,,,;;,,,,,,,,;;;,,,,,,,,,,,,;;;::::ccllllllllllccloodxxkkkkkkkkkOOOOkkkOkkxxkkOOOOOOOOOkkkkkkkkkOOkkxxkxxxxkOOkxdoxkdddddddxk00KKXXXKKK0Okxxkkkxkkxdoooddddxdddddxxdddddddxkkxdolllcclooolcccccc:cccc:::::::::::ccccccllllllllllllllllllll
oooooooooooooooooooooooooodddddddddddoooddooool:;cllllllooddoolc:;,,,;,,,,,,,,,;;;;,,,,,,,,,,,,,;;:;:::cccccccclllloodddxxxxxkkkOOOOOOOOOOOkkkkOOOkOOOOOOOkkkOOOkkOOkxxxxxxddxkkkxdodxxxddxxkkO00KKXXXXKK0Okkkkkkkxkkkxooloooooddddddddxddxkkkkkdllodooooolc:::::::;:ccc:::::::::::cccccclllllllllllllllllll
ooooooooooooooooooooooooooooooodddoooddoddoooddc,',;:::ccllc:;,;;;,,;;;;;;,,,,,;;;;;,,,,,,,,,,,,;;;;;:ccccc:;:ccllooooddddxxxxxkOkkOOOOOkkOOkkkkOOOOOOOOOOOOOOOOkkkkkkkkkkkkxdxxxxoodxxxkkkOOOO0KKKXXXKKK0OkkkkkkxxxkOkxddooooooooddxxxxkkkkkkkkdlllodddolcc::::;;;;;;::::::::::::ccccccclllllllllllllllllll
oooooooooooooooooooooooodddoooodddoooodddoddoddl;..............';;,,;;;;;;,,,,,,;;;;;;;;;;;,,,,;;;;;;;:::::::ccllllooooooodxxxxxkkkkkkOkkkOOOkkkOOO0OOOOO00000OkkOOOkkOkkkOOkxdddoloodxkkOO00000KKKXXXKKK0OkOkkkkxxkkkOkkkxdoooddoooxxxxxkOOkkkkxddddddolcc::;;:;,,,,,;:;;;;:::::::cccccclllllllllllllllllll
ooooooooooooooooooooodddddddddddddoooododdoooddl;.. .......... .,;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;,;:::ccccclcllllooooodxxxxkkkkkkkkkkkkkOOOOOkkOOOOO00000OOO00OOOOkkxxdddollclodxkOO00K00KKKKXXXKKK00OOkkOkkxkkkkkOOOkxdoolodxxxkkkkxxddxkkOOkxxxolc::,,;;;,,,,,;;;;;;;;:::::cccccclllllllllllllllllll
oooooooooooooooooooooodddddoodddddddoddddooddool;. ........... .,;;;;;;;;;,,,;,,;;;;;;;;;;;;;;;;;;:::;,,;:::::::ccccllloooloddddxkkxxxxxkkkxxkkkkkkkkOOOOOOO00000000OkkkxddddoollcclodxkkO00KKKKKXXXXXKKK000OOOOOkkkkkxxkO0OOOOkxdddddoodxkkkxxxOOOOkkxdlc::;;:;,,,,,;;;,,,;;;;::::cccccclllllllllllllllllll
oooooooooooooooooooooodddddoodddooddodddoooodolc;...............,;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;::::::;;,,;:c:::cclllccllllloooodxxxkxxxxxxxxxkkkkkOOkOOOOOOOOO00OOOOxdddooodoollcccloddxkO00KKKKXXXXXXKKKKKK0OOOOOOOOOkkOO000000Okxxkkxdodddxkkxxkkkkxxdoc;,;;;;;,,,,,,,,,,;;;;;:::cccccclllllllllllllllllll
oooooooooooooooooooooodddddoodddodddooddooodolc;'..............',;;;;;;;;;,;;;;;;;;;;;;;;;;:::;;:c::;;;;,;:ccc:::cc:::clcclooooodddddoodddddxxkkkkOOOOOOO00OOOOOkxddoooooodddoollccloodxkO0000KKXXXXXXXXKKKKK0OOO00000000000000000OkkkOOOkxddxkkxxkOkxdolc:;;;,,;;,',,,,,,,;;;;::::cccccclllllllllllllllllll
oooooooooooooooooooooodddddooddddddoooddooool:;;,.............'',;;,;;;;;;;;;;;,;;;;;;;;;;;;;;;::cc:;;;:;;::::::;;:::cccccllooolooddooloodddxkkkkkOOOOOOOkkkxxddollcllllloxxxdollcclooddxkO000KXXXXXXXXXKKKKK0OOO0000000000000000KK0OOkkkkO0OOOOkxxkkxdoc::;;,,,,,,,,,,,,,,;;;;;:::cccccllllllllllllllllllll
oooooooooooooooooooooodddddddddddddooodddoooc:;;,..........',''',;;,;;;;;;;;;;;,;;:;;;;;;:::;;;::::;;;;;;;:::;;;;;::::::cccclloolloodoooodddxxxxkkkkkxxxxddollccccc::clloddxxdollcclloodxkO0KKKXXXXXXXXXXXXKK00OkkO0000000000000000000OkkkOOOOOOkxdxkxxoc::;,,,,,,,,,,,,,,;;;;;::::cccclllllllllllllllllllll
ooooooooooooooooooooooddddddddddddddddddooool:,,,.........',,,'',;;;;;;;;;;;;;,,,;;::;;;;;::;;:::;;;;;,;;;:::,',;;;,;;;;;:::ccclccccccloddddxxxxxxxddddoollccllool:::cllooodddollccccloddxkO0KKKXXXXXXXXXXXKK0OkkkO0000000000000000000000OkkkkkOOxdddxdolc:;;,,,,;;;,,,;;;;;;;:::::cccccllllllllllllllllllll
oooooooooooooooooooooodddddddddddddddoooooool;'','........',,,'',,;;;;;;;;;:;;,,,;;;::;;;;;:;:::;;;;;,,;;;;:;,',,,,,,;;::;;;;;;;:cclllllooddddddddddooollllodxxxdl:;::ccccclllllllcc::clddxkkO0KKXXXXXXXXXXKK0OOkxxkO0000000000000000000OOkkkxxkkkollddlcc::;;;;;;;;;;;;;;;;;;::::ccccccllllllllllllllllllll
oooooooooooooooooooooooodddddddooooodoooooool;''''..','..',,,''',,;;;;;;;;;;;;;,,;;;;;;;;;;;::::;;;;;,,;:::;,''''.',,,,;;;,,;;::::ccllllllooooooooooollloodxxxdddo:,',;;;;;;::::ccccc:ccloxxxkkO0000KKXXXXXK0OkkkocldkO0000000000000OOOOOOkkxxdxxxo:coolcccc::;;;;:;;;;;;;;:::::::ccccccllllllllllllllllllll
ooooooooooooooooooooooooddddddoooooooooooool:,''','.',;,,',,'''',,,,,;;;;;;;;;;,,;;;;;;;;,,;::c:;,;;,;;;:::;,''...',,,,,,;;;:cllcccclllooolllooolllooooddxxxxdoodoc,..''.......'',;::;;:cloddxkkOOOOO0000000OOkkxo;,:ldkOOOO00OOOOOOOOOOOOkxxxdxxxoc:lolccccc:::::::::::::::::::::cccccllllllllllllllllllllc
ooooooooooooooooooooooooddddddddddoooooooolc;;;;;;,'',,,,'',,''',,,,,;;;;;;;;;;;;;;;;;;,,,,,;:::;;,,,,,;:c:;,,'..',,,,,;;:::::cllllcccclllllcclllloddxxxxxxxdooooooc;......      ....''',;:coodxxxxxkkkkkOOOkkxddo:,';coxkkOOOOOOOOkkkkkkkxxddddddo::lollllcccc:::::::::::::::::::cccccllllllllllllllllllccc
oooooooooooooooooooooooddddddddddoooodddolc:;::;,;;,,,,,,'',,''',,,,,;;;;;;;;;;;;,,;;;;;,;;,,;::::;;;;,,:c:;;,,..'',;;;,,,,,;;:cclllcccccccccclodxxxkkkkkkkxdoooooool:,......       .....',;:loodddddxxxxxxxxdoloooc,,;codxkkkkkkkkxxkkkxxkxdddddol::lollllccccc:::::::::::::::::cccccclllllllllllllllcccccc
oooooooooooooooooooooooddddddddooddooddollllc:;,,;;,,,'',',,,'''',,,,;;;,;;;;;;;;,;;;;;;;;;;;;;;::;;;;;:clc:;,'..'',,;,,',,;;;;::ccc:;;:ccloodxxxxxkkkxkkkkxooooooollll:,'....  ...........',;:clllllllooooolcccooooc;,;:lodxxxxkxxxxxkxxxxxxdddolc:coollllcccccc:::::::::::::::ccccccccllllllllllllccccccc:
oooooooooooooooooooooooooodddoooddoooddoolool:,',::;,,''',,,''''''',,,;;,;;;:;;;;;;;;;;;;;;::::;;::;;;:cloc:;,'..''''',,;:::cccc::;:cclodxxxxdddxxxxxxxxkkkdolooooollllcc::;,'..     .........',,,,,,,;;;;:clodddoool:;;::clodxxxxxdddxxdddddddolcccloollllccccc::::::::::::::::ccccccccllllllllllccccccc:::
ooooooooooooooooooooooooooooooooooooooooooool;'',:c:;,''',,,'''''''',,;;,;;;::;;;;;;;;;;;;::cc:;;;:;;;:clll:;;'..''',,;:clcclc:::ccodddddxxddddddxxxxxxkkkkxolloooooollllc::::;,..       ................,cdxxxddddolc:;:cccllodddddddooddddoolcc:clllllllcccc:::::::::::::::::ccccccccllllllllccccccc:::::;
oooooooooooooooooooooooooooooooooodddoooooodl;'',:c:;,,,,;;,''''''''',;;,;;;::;;;;;;;;;::;;;cll:::::;::clllc:;,..',,,;::ccc:::clloooooddddxxxxddoddxdddxxkxxdollllooolllllc:::;;;,..        .....   ..',;cdxdxxdoooooc:;::ccclllooooooolllooolc::cclllccccc:::::::::::::::::::::cccccccllllllcccccccc:::::;;
ooooooooooooooooooooooooooooooooooooooooooodl;''';:c:,,,,;;,'.'''..'',,,,,;;::;;;;:;;;;::::::cllc::::cclllol:;,''',;;;:clc::clodoooooodddddxxxddoodddddddxxxxdoollloolccllccccc:;,,'..            ..,;:clodxxxxdoooool:;;;:::cccclollllcccclc::::ccccccc:::::;;;;;;;;;;:::::::::ccccccccccccccccccc::::;;;;;
ooooollllloooooooooooooooooooooooooooooodddoc,,,',::;,,,,,;;'.'''..'',,,,,,,;;;;;;;;;;;;:c:::clllc:;:cllllooc;,'',;;;::clcccllooooooolloooodxdddddddddddddddxxddolooollllllllllc;,,,,..        ..',;:::codxxxxxdooooolc::;,;::cccccc:::::;::;;;:::::::::::;;;;;;;;;;;;;;;::::::::ccccccccccccccc:::::;;;;,,,
ooooolllllooooooooooooooooooooooooooooooodd:'';;,,;:;,;;,';:,..''...'',,,,,,;;;,;;;;;;;::::::cclcc:;;cloooooc;,',;;,;:ccc:ccloooollllllllllloooddddooodddddodxxddolooollllllloolc:,,,'..    ..',;::::cllodxxxxxdolloollccc:;,,;;::;;;,,,,,;;;:::::::::;;;;;,,,,,,,,,,;;;;;;::::::::ccccccccccc::::;;;;,,,,''
oooollllllllooooooooooooooooooooooooooooddl'.'::;,;::;;;,',:;'..'....'',,',,,;,,;;;;,,;:c:;;:cc::::;;:looool:;,',;;,;ccc:::llollllccccccccccclllloolllooddooddxxdddollllllllllllcc:;,'.....',;;;;:::clooooodddddolllllllcc:;,'',;;,''''..',;:::::::;;;;;;,,,,,''',,,,,,;;;;;;;::::::::::c:::::::;;;;,,,''''.
oooolllllllllllooooooooooooooooooooooooodl,..'::;,,;;;,;,',::;'.......''''',,,,,,;;;,,,;::;;;cc::::;;:clooolc:,',;;;;cc:::clollccc:;;;;:;,,,;::::cccllooooollodddddddoolllcc:::c:::::;;;;::c:::::cclodddddddddddolllllolllc:,..',,'.....',;:::::::;;;;;;,,,,'''''''',,,,,;;;;;;;:::::::::::::;;;;;,,,''''...
oooollllllllloooooooooooooooooooooooodoc;.. .':c:;,,;,,;;,';::'.........''.'',,,,,;;,,,;;:;;;::;;:::::clooolc:,',;;;;::::cclllc:;,,,''''...'',;;:ccccllooddoooddddddxxxdooddooooooooolloddooooollloodxddxxxdxxxxdollllllllll:'..''.....,;:::::::::;;;;;,,,,''''''''''',,,,,;;;;;;;;;;;::::;;;;;;,,,''''.....
oooollllllllloooooooooooodoooodoooodoc,.......;c:;,;;;,,;,',::;..............'',,,;;,'',;::;;;;,,,;::ccloolcc:,',;,,;:c::cclolc:;,'''...  ...',;;:clc::clodooodddddddxxxdxkxxxxkkkkkxdddddddddoooodxxxxxxxxdddoooollollclcccc,.''...',;:ccc::::::;;;;;;,,,,''''''''''''''',,,,,,;;;;;;;;;;;;,,,,,'''........
ooolllllllllooooooooooooddoddoodddoc,.........':c:;,;;,,;;'';::,...............'',;;,'',;::::;,,,,,;:clloolc::,',;;;;:ccccloddoollc:;'...........',;;;,,;;::ccclloooddddddxxxxxxxkkxxxxxxxxxxxxxxxkkkxxxxxddoollllllllcccccc:,,,''',;:cccccc::::::;;;;;,,,,'''''''''''''''''',,,,,,,;;;;;,,,,,''''..........
ooolllllllloooooooooooodddddddddoc,............,::;',;,,;;,',:c:'................',,,''',;:::;;,,,,,;:loool::;,'';::;;:cclloddddddolc;,,,;;;,'..    ............'',,,;::::clooooddddxxkkxxkkxxxxxxxxxxddxddolc:::cclcccccccc:,,,,,;:ccllcccccc::::::;;;;,,,''''''''''''..'''''''',,,,,,,,,,'''............  
oolllllllllooooooooodddoddddddoc,..............';:;,,;;,,;,'';cc,.................',,''',;:c:;;,,',,;:cloolc::,'',;;;;:clllodddddooooc:::;;;;;:;,'.........     .........''''',;:cclloodddoooooooollllooddool;'.';;:cccccccc:;,,,:ccccllllllcccccc::::;;;,,,,'''''''........'''''''''''''''''...........    
ollllllllllooooooooddddddddddl;'................,::,',;;,,,'',:c:'.................','''',;::;;,,'',;:clolccc:,'';;;:::coooodddddddddolccc;,,;;::::cc::::;;;,,,,,,'................'',;:c:;;;;,,'...',,;:clc;....',,;::::cc;;;;;:cc:coooolllllllcccc::::;;;,,,,''''''............'''''''''............      
llllllllllooooooooddddddddoc;'..'...............':c:,';;,,,,'';::,'.......  ........''''',,,,,,,,''',;clolc::;,',;;;::::coodddxxdoodoollllcc:;;;;;:clooolllloddoodoollc:,'.......................    .............',;::clc:,,;cll::coddoooooollllllcccc:::;;;,,,,,''''..............................        
lllllllllloooodddddddxxdo:'....''.'..............:c:,',;,',;,',;::,..................'''',,;,,,,''''',:lllc:c:,',,,;::::clooodxxxdddollcloool:;,;;;::loooolloddddxxxxxxxxxdollc:,'..................  .......'....',:cccc:;;:clc::coddddoooooooolllllcccc:::;;;;,,,''''..........................           
llllllllllllllloooooddl:'........................;:c;'';;'';;'',:c:,....................'',;;;,,,''',,:cllccc:,',,,;;:cccclloodddxxxdddoooooolc::;;,;::cclllllldddddxxxxkOOkkkkkxxdooollllccccccc:;;,,;::;,,;::;,,;:ccc::;:lllc::cdddddddddddoooooolllllccc:::;;;,,,'''........................             
c::::;,,,,''''''''''''...........................';c:'.,:;'';,'';cc:,.......  ...........'',;;;,,,,',,:ccccc:;''',,,,;:ccllooddddddxxddddooodolc:;;,;;;;;;:clclooodxxdddxxxxxxkkxxkkxdodxxdooolcccccccccccccccclllccllc:cclllccclodddddddddddddoooooollllccc:::;;;,,,'''....................                
................................................ .,cc;.',;'.,;'',:::;,.......     .........',;;,,,''',;clccc:;,',,,,,;;:ccclodddddddxdddoooooooc:;;,,,,,,;;;:::ccloddxdddxkkxxxkkxxxdooddxdddddoooolllcllcccllooooolllcclolccccloooooooodddddddddoooooolllcccc::;;;,,,''..................                  
.........'..... ...................................;c:'.';,'';;'';:::;'.......     .........',;,,'''',;clllc:;,,,,;,,,,;:cllooodddddoooooooolooollc;,,''',,;;;,,;;:ccllloddddddddxxxxdddxxddxxddddocclloolloooddddolcclllllcclloooooooooooooooooooooooolllllccc::;;;,,'''............                       
............  .....................................'::,..,:;'';,',;:::;,.......      .......',;;,,,,,,;cllc::;;;;;;;;,;;:cllloodddoolclllooolllllool:;,'...'','''...''',,,,;;:cclloooooodxxdddlllc:coddooddddddddoc::clolccccllllllllllooooooooooooooooollllccc:::;;,,,''.......                            
.................................................. .,::'.,::,.','',::;;;,'.......     .......',;,,''',;clccll:;;;;;;;:::clooloodddollodoollloooolloolcc:;,,'....................'',,,,,;;;;;;;::::coxkxddddddddooc::lool::::cccccclllllllllloooooooooooolllllccc:::;;,,''.......                            
'.................................................. .;c;'.,c:'.','';:;;:::,.......      ......',,,,''',:lllllc;;;;;:cc::clooodddddddoddddolcllloooloooooc::;;,,'...............    ........,;;:::ldxxxxxxxxxxdol:::lolc;;:c::ccccccccccccllllllloooooooollllllcc:::;;,,''.......                            
''''...............................................  '::,.':c:'.,,,,;::::::;'.......      .....''',,'',:::cllc::;;;:cc:clllloddxxdddddoddxxolllooooooddddollcc:::::::;;;,,,,,,,''.....',,;;;;;;clddxxdxxxxxdool:;clllc:::c::::::::::::cccccclllllllooooollllllccc:::;;,,''......                            
..'''..............................................  .,:;'.,cc;'.,;;;:;;;:::;'.......      . .....'''',;::ccc:;;;,;;;::ccllooddxxddddddodxxxddddoddooooddxddoooolllllllllcccccccccccc:::::::::codddoddxxxdddol::cllc:::::;;;;;;;;;;:::::::ccccclllllooolllllllcccc::;;,,''......                            
....................................................  .;:;'.,cc;'.';:::;,;;::;,........        ....'''',;:clc:;;;;;;;::ccllooodxxdddddxxxxxxxxxxdddddooddxxdooddddxxddoollccclllllccc:ccccccclooodddodxxxdddlcclooc::::;,'',,,,,,,,,;;;;:::::cccllllllllllllllcccc::;;,,''......                            
....................................................   '::;'';cl;..';:::,,,,;;;,........        .....'',;:cccc:;,,;;;::::cllooodddddxxxxxxxxxxkkxdxxxxdddddoodxxxkkkkkkxxddddddoolccccllloooloooddxxddddddolcllol:;;:;,..''''''''''',,,,;;;:::ccccllllllllllllcccc::;;,,''......                            
.....'...............................................  .,::,.':ll:'.';:cc;,',,;;,'.......         ....'',,;;:::;;;;;;;:::ccllloooddddxxxxxxkxxkkkxxxxxxxoooddddxxxxxxddooodddxxxxddoollllloooooddxxkkxddddoccloc:;;;;'............'''',,,;;;:::cccclllllllllllcccc::;;,,,'.......                           
.....'..'............................................   .,:;'.,:lc:,..,:cc:;,',,;;,........         .....'',;;;,,,,,;;;;;:ccllooodddxxxkxxxkkkkkkkkkkkkkxxxxxxxxxxxxkkxxxxxdddddddddooolloooddddxxkxxxxdolclooc;;;;'................''',,,;;:::cccclllllllllllcccc::;;,,,'......                            
....''.',............................................   ..;:;..;c::c;..,;cc:;''',;;,........         .......',,,''',,;,;;:cccllooooddxxxxkkxxxxxxxxkkxxkkkxxxxxxxxxxkkOOOOOOOOOOOOkkkkkxdddxxxxxkkkxxxddoccooc;,,,'.................''',,,;;:::cccclllllllllllcccc::;;,,''......                          ..
....''.''............................................   ..';:,.':c;:c;'.';cc:;''',;;,'........         ......'''.''''',,;:::ccllooooodxxxxkxdddddxxxxkkkkkkxxxxkkkkkkOOOOOkkkOOOOkkkkOOOOOkxxxxkkkkkkkdollll:,,,,'''''''''''''''''''''',,;;;:::ccccllllllllllcccc:::;;,,''......                       .....
....'...'.............................................  ...'::'.,::;;::'.';:::;'''',;,..........           .........''',,;;:::ccllooddddxxxddxxddddxxxxxkkxxxxxkkkkkOOOkOOkkkkkOkkkkkOOOOkkkkkkkkkkxxxdoool;,,,;,,,,,,,,,,,,,,,,,',,,,,,;;;:::ccccllllllllllllcccc::;;,,''......                    ........
.. .''.',............................................    ...':;'';;;,,::,.';;;;,'''',,,...........           .........'',,;;:::clllloddddxxxddddooodddddddxxxxdxxkkOOOOkkkO0OkkkOOkkkOkkkkkkkkkOkkxxdddddl:;;:::;;;;;;;;;;;;;;;;;;;;;;;;;::::cccclllllllllllllccc:::;;,,''......                   ......'',
.  .''.'''...........................................    ....,:,',;;;'';:;'.,;;;,,'.',;,'.........              ........'',,;;:ccccllooodxxxxddoooodooooddddddddxO000OOkkkkOOkkkkkkkkkxxxxkkkkOOOkxddoool:;:cccc::::::::::::::::::::::::::ccccclllllllllllllllccc:::;;,,''......                .......'',,;
.  .'..''......'.....................................     ...';;,',:;,'';:;,'',;;,'''',;,'........                  ......''',;;;;:ccclloddddddollodooooodoooooodxkkkkxxxkkkkxddxxxxxddxxkOOOOOOkxdooooc;'',;;::cccccccccccccccccccccccccccccllllllooollllllllccc::;;,,,''......             .......''',,;;:
.. .''.',......'.......................................   .''..;:;',;;,'',::;'',;;,,,'',,,'.........                 .......'',,,;;;;:cclooooddolllooddooooollllllodddddxxkkkxoooodxdoodxkOOkkkkxddool:'..'''',,;;;;;;;;::cccccccccccllllllllllllloooooolllllcccc::;;;,''.......          ........'',,;;;::c
.. ...',,......'........................................   .,...;:,',;,''',;:;,',,,,,'''',,'.........                   ........',,,,;:::clooooooooloooollooo:;;:ccloooddddxxddddoolloodxxkkkkkxdddol,.......''',,;;;;,,,,,,,;;::ccccllllllooooooooooooooollllccc::;;,,''......         .......'',,;;;::cccl
.. ...',,'.'...'........................................   .;;...;:;,,,;,',,,::;,,''','''','..........                     .........''',,;:cllloooollllccllool:;;;:coooooodooddddolcloddxxxkkkxxddoc'...........'',,;;;;;;,,'''',,,;;;;;;::cccllooooooooolllllcc:::;;,,''......       .......'',,;;:::ccclll
.. ....''.''.........................................       ':,..';:;,,;;,',,,;::;'''',,',,,,'..........                          ......'',;:ccllllllllllclllllc:,',clllloooooooooooooodxxkkkxxddo:...............''',,;;,,,,,,,,,,,,,,,,,,,,,;;;;::cllllllllccc::;;,,''.......     ......''',,;;::ccclllooo
..  ...''.''............................................    .;:'..',;:;,,;,','';::;,'''''''',,'.........                               .....',::::ccccccclccc:;;;,'';:ccclllooooloddddddxxxxdddol;.................''',,,,,,,,,,,,,,,,,,,,,;;;,,,,,,,,;;::ccccc::;;,,'''.......  .......'',,;;;:cccllllooodd
... ..',,..'...'...'....................................    .'::'..',;:;,,,,,,'',;::,..'',,,,,'........                                     ....'',,,,''..'','',,;,,,;::::cllllcclodddddxxdddooc;...................'',,'''''',,,,,,,,,,'',,,;;;;;;,,,''',,,;;;;;;;,,''...............'',,;;::cccllloooddddd
.'.. ..,,'.'...'...'.....................................    .;c;...',;::,',,,',,,,:c:'.',,,,,,,''.....                                          ........ ...'',;:;,'',,,;;;;;:::::looodooool:;,'.....................'''',,''''',,,,,,,,'''',,,,;;;;;,,,''',,,,,;,,,''............''',,;:::ccllllooodddxxxx
.''....','.''..'...'...................'..................    '::;...'';;:;'',,'',;;;c:,.',,,,,''''.......                                                 .............'.....,;;;;::ccllc:;,,,,'......................'''''''',,','''',,,''''''',,;::;;;,,,,''',,,,,,,'.........'',,;;;::clllloooddddxxxxxk
..''...''..''..'...'......................'.................  .,cc;...''',;;,,,,'',;;;::;'.''','''''........                                                                  ...'',,;,,'''',;,;,'''...................',''''''''''''',,,''''''''',,;::::;;;,,,'''''',,,'''....'',,;;::cclllloooddddxxxxkkkk
...''..''..''..''..''.............'......''..................  .:cc;'..','',;,'''',,,,;:c:,..'''''''''.......                                                                   ........',;;;;,;;,,'''............'',,,;,,',,,'...'''''''''''''''''',;;;;;;;;;,,''''''',,,,,''''',;::ccclloooddddxxxxxkkkkkk
...''..''..''.','.',''''................'''................... .;cc:;..''''',;;,''',,,,;:c:,...'''''',,'......                                                                      ..',;;:::;,,,,'''....''''''''',,,,,'',,''.........''''''''''''''''',,,,,,,,,''''''',,,,,,,,''',,;:cllodddddxxxxxkkkkkkkk
....''',,'',,',;,.',''''.................'''..................  .::::,..',,'.';;,''',,,;;:::;'...''''''''.......                                                                 ...'',,,,;;::;,,''''''''''''',,,,''''''''...........''''''''''''''''',,,,,,,,,,''''''',,,;;;;,,'''''',;:ccodxxxxkkkkkkkkOOO
....''',,,,,,',,'.''''''''''................................... .';:::;..',,''',,,,'''',;;:::;,...'''''','.......                                                           ......'''''',,,;;;::;;,''',,,,''',,,,''''''''......'''.....''''''',,,,,'''',,,,,'''''''''''',,;;;;,,'''''''''',,:codxkkkkkkOOOOO
'.....'',,,,,'','..'..'''''''........'..'.....'...'............. .'::::;...,,''',;;,'''',,;;;;;,''''''''''''......                                                        .';;,....'''''',,;;;;;;;;;,,''','''''''',''''''....'''......'''...'',,,'',,,,''',,,,''''''''..'',;;;;;,,'''''''''''',;:coxOOO000Ox
'......'',,,,'','..''''''''''.................................... .,;;;;;..',''''',;;,'',;;;;;;,;;,'.....''''.. ...                                                     ..,;;,.....'''''',,,,;;;,;;::;;,,'''',,,'''',,,,''.....'''......''....''',,,''''''''''''''''''''''',,,,,,,''',,,'''','''..';codl:;,'
,'......',,,,'.''..'...........................''..'.............. .',,,;,'..'''',',;;;'',;;;;;;;;,,'.....'''...                                                        .';;,'. .....''',,,,,,;;:;;;;:::;,'','',,,,''',,,''....''...'''.....'''''',,,,,'''''''''''''''''''',,,'''''..''''''''''''....... .,c
;,'.....',,;;,'''..'...........................'''''.............. ..;;,',,'....',,'',;;,',;;;;;;,,'',,'..........                                                    ..',,;,.  .....'''',;;,,,;;:;;,,;;:c:,',,,,,'',,,,,,''..................'''',,,,'''''''''''''''''''',,,,,''''.................... ....
','......,,,;,,''..''.'..................''..........................';:,''''....',''',,,,,,;;;;;;,''''''''.......                                                  ...',',;.    ......''',,;,,;;;;;;;;;::::;;,''''',,,,'''''.................'''..''',,,,,'''''''''''''''',,,,''''.................. ..   .
....... .',,,',,'.'''...................''...''.......................,::;,'''....',''',,;;;,;;,,,,,'..''''''.....                                          ....    ..',,,,.      ....''''''',,;;;;;::::;;;,,,''''''''',,,,'.......................'''',,,,''''''',,,''''''''''''''........  .. ..   .'..  .
.......  .''''''...'.....................''.''''......................':::;;,'.....',,''',,,;;,,,,;;;,'.'''',,'...                                        ...........',,;;.        .....''''',;:::::;::;;,,'''''',''''''''''''......................''',,,,''''''',,,''''''''''''''''....            ....  .
''''..   ................................''............................,::;;;;,.....',,'''',,;;;;,,;;;,'''''''......    ..                            ...... .......'',;;,.         .....''''',;;::;;;,,,,,''''''''''..''''''.......................''''',''''''',,,,''''''....''''''..               ..    
''.'..   ..................................''..........................';;;:;;;,'.....',''''',;::;,,,,;;,''''.............                           ..............'',;:,.           ....','''',,,,,;;,,,,,,',,,,'',,''''...'''.......................'',,,'''''''''''''''.......'''.                ...    
.''''..  ...............................................................,;;;;;;;,'.....''''''',;;;:;,',;;;;,'...............                      .........    ...'',;:;.             ..'''''..'',,;;:;;;;,,,,;;;;,,,,,,,,'...........................',,,,'''''''''''''''.......''.                 .'.    
.''''..  ...............................................................,;;;;;;;,'.........'''''',;;;,,',;;;,'...............                   ............  ....',;:;.              ....''''..'',;:::;;;;;;,,,,;;;,,',,,''..........................'',,,''....'..'''..........'..                 ..     
....''.  ....  ...................................'''''.....'............;:;,,,,,'..........''''''',,;;,''',,,,'.............                  ....  .............,;;;'                ....'''...'',;;;;;;,,,;,,,,,,,'''''''''...'''....................''''....''''...............                         
....''..  ...   ..................................''''''...''............,;;;,''','...........'''','',,;;;,,,,,,,'............             ......'.......'''....,;;;,,.                 .....''....'',,,',,,,,,''''''''''''''''''',''....................'''......................                          
.....''. ....   .................................'''''''...''.............,,,,,''',,.....'.....'',,,''',,,,,;,,'''..............        ................'''''',,,,,,'...                 ....'''....'''''''''''''''''''''''''''''',,,''...............'''''.......................                          
......'......    ..................................''''....''............',,,,,'''',,'....''......',,,'',,,,,,,,''''''''.....................................',,,,,,.  ..         ..      ....',''...''''''''''''''''''''''''''',,',,,''...............'''........................                          
.............    ..................................'''''...''..'..........,;;;,,,'.',,'....''.......'',,,,,,;,,',,,,''',,'...........''..'............'....',,,,',;,.  ..          .... ........'''...'''''''''''''''''''''''''''''',,,''.........................................                          
.............    ..................................'''.'..','.''..'.......,::;;;,''..','...'''.........',,,,,,;,,,,,,,,'''.......',,'''''''''........',,,,,,'','';c;.  ...          ............''''...'''''''''''''''....''''''''.',,,''''........................................                         
.............    ......''..........................'......','.''...........';:::;,,''.'''....''''''......'',,;:ccc:;,,,'.....,;;,,,,''',''.''''... ..',,,,,,,''';lc.  ....           ...........''''...'''''.............'''''''''.''''''','.......................................                         
.............    .........................................',..''..'.......  ..',;;;;,,'''''..'''''',,'',,;;;;;:cloolccc:;,,,,;;;;::;;,,,,'',,,'......'''''''''';ll,   ....             ..........''''..',,,''............'''''''''..'''''',,'.......................................                        
............     .....'.........''''......................,,..''.'........      ...,;;,,,,,'''''''..',;;,;:ccccccllllllc:,,,,,,,,;;;;,,',,''''''',;;,,,;;;;;,,;:c,.  ......             ......''.'',''..',;;,'.....''.....''',,,,'''''''''''''....................'''''..............                       
..'..''''...     ...''''''''.''''''.''...............'''..,'..'............         ....',;;,'.......',;;;;:cllolcccccc:;,,;,,,,,,;;;,,,,'''',,,,,;::cccc::;,,::'.   .......              .........'''...',;:;'.'..'.......'',,,,''''''''''..''.................'''''''...............                      
........'...      ...'',',,''''''''''''....''.''.....'''..'.................            .......',,''''',;::::cllooolccc:;,,,,,,,,,,,,,,,,,,,'',,,;;:::::;;::;;;'.   ........               .. ...........'',;:;,'..'..''...'''',,'''''','....''''............'''''''''''''..............                    
............       ......','''''''''''''...'..''''''........................                   ...'',''',;cccclllooolll:;;,;,,;;;,'',;;,,,,;,,,,;;;:cccc:::::;,.    ........               ...............',;;:;'''','''..'''''''''''''''......''''..........'''''''''....................                  
............              .....'''''''''......'''''.........................                       .......,;:clloooollc;,,,,,,;;;,;;,,',;;;;;,,,;;;::::::::;;,.   ..........              .................'',,;,''',,,'''''...'''''''...........''''''......',,'''.........................                
............                   .......'''''''''......''......................  .                           ...',;cllool:;;:::;;,,;;;,,;;;:::::;::ccccllllc:;,.   ............              ....................'......'''''....''''..............''''''''.....''',''..........................              
'.''.'.....                            .....'''''.'''........................                                    ....'''',;;;:;;;;;;;;;;::;;;;;;:clllllllc:,..  .............             ....................................'''''................'',,;;,...',,'''.........................''...           
..'..'.....                             ............''.......................                                             ........'',;;;:;;;;;;;:ccloooolc;'................               .....................''''''''.....'''''.................'',,,'''...''''''...............................         
'.''.'....     ...                ..............''''..........................                                                      ........''',,;:ccc::;,'.................               .......................''',,''......................'''....',;;,...,,'''.................................      . 
'.'..'....     ....       .......'..',,,''......'''',''.......................                                                                ..................   .........        .       .......................''''............................''',,'''...''''''...............................     ....
.....'...     .........''''''''''....','........,;;,''.........................                                                                                . ..........         ..      .........................................''''''......'''...',,,'..',,''.....'..........................     ....
'.......      .....',,''.............',,'''......'''','........................                                                                            ...................      ...     .....................................'..................','''''....''''','.............................     ....
'......      .... ..''..........'.....',;,,'.....''''''........................                                                                       ......................  ....   ...     ..................................'''......................'','...',,'................................    .....
'.....      ....    .','..........''''',,;,'......'''','........................                                                                              .............     ...  ...      ...........'.....................''''.............................''''''.............................   ......
.....      ......    ...................',,'....''''............................                                                                            ...............           ...     ...........'''''.........''''......................................'''...............................   ......
'...       .......    .,'.........''''..','.....................................                                                                 ...     ...................         ....      .............''..........''.......................................''''..............................   ......
...       ...''...     .'''''''''''.'....'''....................................                                                                           .     ..........          .....     ............''''''.......'''''.........'''''.......................''...............................   ......
..      .....''....    .''''''''''',,,'''''.....................................                                                                                ...........           ....      ........'''''''''..................................................'...............................   ......
       ......''.....    .',,,'''''''''',,,'.....................................                                                                              ...............        ......     .........'''''',''.............'..............................'....................................   ......
     ........''..'...    .'''..'',,,,,,,,'......................................                                                                           .....   .........         ......     .........'''''''''...............................................................................'..  ......
    .........''..''...    .,,''.'''',,,,,,'.....................................                                                                        ........ ............        ......      ...........'',,''.'''...........................................................................'..  ......
  ......'....''..''''..   ..'''',,,,;;;,,'.......................................                                                                      ........    ...........       .......     ............'''............... .........''...'.................'...........................................
 ....''''....''...''''..   .',''''''',,;;,''..''.................................                                                                       ......     ............      .......     ...........''''''.............     ......'.............'...................................................
...''''''.....'...'''...    .''''',,,,,;;;,'...'.................................                                                                       ....      .............      .......      ...........''''''................  .............................................................'.........
..''''........'..........    .,'''',,,,,,,''.....................................                                                                     ......      ............       ........      ...........'''............................    ...........................................................
'''''........''........'..   .'''.',,,,,,''......................................                                                                     ......    .................     .......      ........................................... .............................................................
'''''........''...'....','.   ..''''',,,'........................................                                                                    .....      ..................   .........      .......................................''...............................................................
'''''......''''..'''...'','.   ..''',,,'.........................................                      .    .                                         ....     .   ..      ...................      ...............'''.....................''''''...........................................................
'''''....'''''''''''...',,,..  ..''''''...........................................                          ..                                                                      ...........      ...............''......................'''''...........................................................
'''''.......''''.'''..'',,,'.   ....''............................................                          .....                                   .                                 .........      .......'...............................''''''..'''....................................................'
'''''.....'''''..'''..',,,,'.   .......................''.........''..............                           ......                                ..                                 .....  ..       .......................................'''....'''...................................................',
.''''......'''''.','..''''''.    ......................'''........''''.............                           .......                              .                                   .........      ........................................'...''''...................................................',;
...'''''''''''''.''''''''''..    ..................................'''.............                             .........                                                              .........       ........................................'''''''...................................................',,
''..'.''.''''''''',,,,,,,'...     .''..............................................                               ..........                                                            ........        .......................................'''''''.............................................'....',,'
.'...''..''''....'''',,,,'...     .''..............................................                                 ............                                                         ........        .......................................''''''''................................................'''.
.'..'''...'......',,,,;;,'...      .''..............................................                                   ...........  ..                                                    .......       ....................'''''................'.'''''...........................................'''..'''.
.....'''.''...'...'',,;;,'....     .................................................                                   ............                                                        .......     ....................'''''''...............'..'...............................................''''''''
.....''''''.......'',,;,'.....      ................................................                                       ........                                                          .....      ....................''''''..............................................................''''''''''',
......,,,,'''.'....'',,,'......     ................................................                                            ..                                                            ....      ....................'''''''................''..........................................''''''''''',;
......',,,'.'.'....',,,,'.....      ................................................                                                                                                          .....     ....................''''''''...............''.....'.....................................''''''',,,;:
......',,''''''.....'''''......     ................................................                                                                    .                                      ....     .....................'''''''.....................''............................'.......'''''.'',,;cl
.......',,''.......'',,'........     ...............................................                                                                   ..                                      ....      ....................'''''''.....................'''.........................'.........'''...',,;:co
)";
    cout << edpic;
}