//  Created by YIM on 26/04/2023.
#include <iostream>
using namespace std;


void pic() {
    string edpic = R"(
      XXXXXXXXXXXKXXXXXXXXXXX00000KXNNNNNXK0Ok0KK0dod0NNNNNNNNNNNNNNNNXXXNXXXXNNNNNNNNNNNNXXXNNNNNNNXXNNNNNXXNXKXNNNNNNNNNNNNNNNNNNNNNXK0OKK0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxxooodkxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX00
XXXXXXXXXXKXXXXXXXNXK0000KXXNXXXNNNX00KKXNN0dod0NNNNNNNNNNNNNNNNXKXNXXXXNNNNNNNNNNNNXXNNNNNNNNXXNNNNNXKXXXNNNNNNNNNNNNNNKKNNNNXXK0OOKXKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxdooodxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKKKX
XXXXXXXXXKKXXXXXKXXX0KKXXXXNNXK0XNNXKXNNNNNOooxKNNNNNNNNNNNNNXXNXKXNXKXNNNNNNNNNNNNXXNNNNNNNNNXXNNNNNNXXXNNNNNNNNNNNNNX00KK0OKKO0XK0XNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXkxxdolodxxxONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKXXNN
XXXXXKXXX0KKKKXK0KNXXXXXXXXNXKO0XNNNNNNNNNXOookKNNNNNNNNNNNNNXKXXKXNNNNNNNNNNNNNNNXXNNNNNNNNNNXXNNNNNNXKK0KNNNNNNNNNNNK0XX000000KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkxxdoloxxxxONNNNNNNXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKXXNNNN
XXK00KXXXKXXXXXXXXXXXXXXXXXXXKKXNNNNNNNNNNXkookXNNNNNNNNNNNNNK0XNXNNNNNNNNNNNNNNNXXXNNNNNNNNNNXXNNNNNNX0KKKNXKKXNNNNNNX00XX0KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxxxdoloxxxx0NNNXXNNXKKXXXXKKKKKKXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0KXNNNNNN
00OOKXXNXXXXNXXXNXXXXKK00KXNNNNNNNNNNNNNNNKxooOXNNNNNNNNXXNXKO0XNNNNNNNNNNNNNNNNXXXNNNNNNNNNNNXXNNNNNNNK0KK000XNNNNNNNNKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxxxdoloxxxx0XXXXXXNXKKKXXKK00OOkkkkO00KKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK0KXXNNNNXN
0KXXXXXNXXKXNNXNXKKK000KKXXNNNNNNNNNNNNNNNKdod0NNNNNNNNNK0KKKKXNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNXXNNNNNNNK0K0000XNNNNNNNX0KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0xxxollodxdx0KKKK00OOkkkOOOkdolcccllodxkkOO00KXXXXNNNXXXXXXXNNNNNNNNNNNNNNNNNNNNNX0KXNNXXXXXX
XXXXNXXNNX0KXXXXK00KKXXXNNNNXNNNNNNNNNNNNN0dod0NNXXXXXK000KXNNNNNNNNNNNNNNNNNNNXKXNNNNNNNNNNNNXXNNNNNNNKKXKKXXNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXOdddollodddxO0kxollc:::clolc;;;,,,,;;:cclodxkOO0KKXXXXXXXNNNNNNNNNNNNNNNNNNNNNXXXK0XNXXXXXXXK
XXNNXXNNNXKXKKXXXKXXXXXKKXNNNNNNNNNNNNNNNXOooxKNNXXNNXKKKXNNNNNNNNNNNNNNNNNNNNNXXXKXNNNNNNNNNNXXNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKOdddollloolclc::;;;;,,,;;;;,,;;,,',,,,,,;;;:lodxkOO0KKXXXXXXNNNNNNNNNNNNNNNNNXXXXKKXNXXXXXXXK
XNNNNNXXXNXKKKXNNXXXKKK0KXNNNNNNNNNNNNNNNXkookKNNXXNXXNNNNNNNNNNNNNNNNNNNNNNNNXXKXXNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKKKK0xoollcccc:;;;,,,,'',,'''',,;:;,'''''''',,,,;;;:clodxkO0KXXXXXNNNNNNNNNNNNNNXXXXXX0KXXXXXXXXX0
NNNNNNNXNNXKXXXXXK00KKXXXNNNNNXXXNNNNNNNNXkookXNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKXXNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN00NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXK0Okdlccc::;;;;;;;,,,,,'''''',,;;,''...'''''''',,,;;;;;:clodkO0KXXXNNNNNNNNNNNNNXXNXXXKKXXXXXXXXX0
NNNNNNNNNNXXKXXXKKKXXNNNNNXXXXK0KNNNNNNNNKxodOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNN00XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK0Okxkxoc;;,,,,,''',,,,''''.',,;,,'....''..........'',,,,;;;::loxO0KKXXNNXNNNNNNXXXXXXXXK0XXXXXXXXXK
NNNNNNNNNXK00KXXXXNNXNNNNXK0KKKKXNNNNNNNNKdod0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNXKKXNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKXNNNNKKKKNKOKNNNK0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKK0OOkkxdl;,,,'''''......''',,,,;::;,,''''''...........''',,,,;;;;:coxO00KKXXNNNNXXXXXXXXXXXKKKXXXXXXXX
NNNNNNNNNXXKXXNNNNNNNNNNXKKKXXNNNNNNNNNNN0dox0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKKKK0KXNNNNNNNXKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKKNX0KKOOO0OkO0XXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXK0OOOxdoc;,,'''''''''''',;::cccccllllccc:::::;;;;;,,''....''',,,;;;;::coxO00KXXXXXXXXXXXXXXXXXK0KXXXXXXX
NXXXNNNNNNNNNNNNNNXKKXNNNXXNNNNNNNNNNNNNX0doxKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKXKKXXXXXXNNNNNNNNNKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKXKX00K0kO00kk0OOOO000KXXNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKK00OOxdl:;;,,''''',,;;:cclllooooooooooooollllllccccccc:;,,''''''',,,;;;::cldk0KKKXXXXXXXXXXXXXXKKK000KKKKK
NNNNNNNNNNNNNXXKKKKKKXNNNNNNNNNNNNNNNNNNXOookKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKXXNNNNNNNNNNNNNNNXXXXNNNNNNNNNNNNNNNNNNNNNNNNNX000OOOkkO0K0O0O0KXXXXXNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXK00Okdl:;,'''''',;:clloooooooooooooooooooooooolllllllllcc::;;,'''.'',,,,;;;::ldO0KKXXXXXXXKKKKKKKKK0000O000
NNNNNNNNNNNXXK000KXXNXNNNNNNNNNNNNNNNNNNXkookXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNXKXXXXXXXNNNNXNNXNXKNNNNNNNNNX0KKKK000KXXXXXXNNNNNNNNNNNNNNNNNNNNNNNXXXXNNNNNNNNNNNNNNNNNNNXXXXXX00Okxoc;,,'''',;:looooododdddoddddddddddddooooooooooolllllccc::;;,'''',,,,,,;::clxO0KKKKKKKK00000000OOOOOOOO
NNNNNNNXXXXXNXKXXXNNNNNNNNNNNNNNNNNNNNNNKxodOXNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKXXNXKXXXKXK0XK000O0XNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNNNNNNNNNNNNNNNNNXXXXXXK000kdoc;,,''',;cloddddddddddddddddddddddddddddddddddoooollllcccc::;;,''',;;,,;;::ccdkO0KK00000OOOOOkkkkkOOOOO
NNXXXXXK0KXNNXNXNNXNNNNNNNNNNNNNNNNNNNNNKxodONNNNNNNNNNNNNNNNNXXXXXNNNNNNXXNXXXXNNNNNNNNNNNNNNNNNNXXXKKK0OOKK000000KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXK000kdl:;,''',;clodddddxxxxxxxxxxxxxxxxxxxdddddddddddddddoollllllccc::;;,'',,;;,,;:::cdkOOOOOOOOkkkkkxxxxxxkkkk
NXKK000KKXXNNXXKKKKXNNNNNNNNNNNNNNNNNNNN0dod0NNNNNNNNNNNNNNNNNXXXNNNNNNNXXKK0OOKXNNNNNNNNNNNNNNNXXXXXKXXKKKKKXXKXNXNNNNNNNNNNNNNNNNNNNNXKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXK000koc:,,''';:loddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddoooollllllcc::::;,,,,;;,,,;::coxkkkkkkkxxxxxxxxxxxxxxx
NXKKKXXXNNXXXKK000KXXNNNNNNNNNNNNNNNNNNX0dox0NNNNNNNNNNNNNNNNNNNXXXXXXKKKKKK0KKXXNNNNNNNNNNNNNNNNNXXXXNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKK00Oxoc;,'''';cloddxxxxxxkkkkkkkxxxxxxxxxxxxxxxxxxxddddddddoooooolllllcccc:::;,,;;;;,,;;:codxxkxxxxxxxxxxxxxxxxxx
NNNNXXXXKKK00KKXXXXNNNNNNNNNNNNNNNNNNNNXOdoxKNNNNNNNNNNNNNNNNNNXXNXX00KXXXXKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNXXXXK00Oxoc:;,'',;cooddxxxxxxkkkkkkkkkkxxxxxxxxxxxxxxxxdddddddddoooooooollllccccc::;,,;;;,,,,;:coddxxxxxxxxxxxxdddxddd
NNNNXKK00KKXXXXNNNNNNNNNNNNNNNNNNNNNXXXKkookKNNNNNNNNNNNNNNNNNNNNNXXKKXNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKXNNNXNKKK0KXK0KXKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKK00Oxoc:;;,',;cloddxxxxxxxkkkkkkkkkkxxxxxxxxxxxxxxxdddddddddoooooooooollllcccc:::;,,,;;,,,,;:coddxxxxxxxxxxxxxxxddd
KXNNXKKXXXNNXNNXXXNNNNNNXNNNNXXXXXKKK000xodkXNNNNNNNNNNNNNNNNNNNXNNXNNXNNXXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNNNNNNNNNNNNNKXKKKK0OO000O00KXKKNNNNNNNNNXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK000kdc:;;;,',:lodddxxxxxxkkkkkkkxxxxxxxxxddxxxxxxxdddddddddddoooooooooolllllcccc::;,,,;;,,,,;:codddxxxxxxxxxxxxxxxx
0KXNXXXNXXXNNNNXXXNNXNNXNXXXXKKKK0KKKKK0xodOXNNNNNNNNNNNNNNNNNNNXXNNNNXXXKKKKXNNNNNNNNNNNNNNNNNNXXXXKKKXXXXXXKXKKXNNNNK00O00O0XK00O00XNNNNNNNNNNNNXXXXNNNNNNNNNNNXXXXXXXXXNNXXXNNNNXXXXK000Odl:;;;,,,;loddddxxxxxxxxxxxkkkkkkkxkxxxxxxxxxxxxxddddddddddooooooooollllllcccc::;,,;;;,,,,;:lodddxxddddddxxxxxxd
XXXXXXXXXXXXXNNNXXXNXXXXNXK000KKXXXNNNX0xodOXNNNNNNNNNNNNNNNNNNKKKXXXKKKOO00KXNNNNNNNNNNNNNNNNNNNXXKKKKK00KK0000O0NNNNNKKXKXXKXNXKKXNNNKXNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXK00Oxl:;;:;,,;clodddxxxxxxxkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxdddddddddooooooolllllllcccc:;,,,,;;,,,;:cloddddxxddddxxxxxxx
XXXXXXXXXXXXXXXXXKKKKKKXXXXXXXXXXNNNNNN0dox0NNNNNNNNNNNNNNNNNNNXK0000000OKXXXNNNNNNNNNNNNNNNNNNNNXKKKXKK00KKKKKKKXXNNNNNNNNNNNNNKKXNNNNXXNNNNNNNNNNNNNNNNNNNXXXNXXXXXXXXXXXXXXXXXXXXXXXK0Oxl:;;;:;,;:loddddxxxxxxxxxxkkkkkkkkkkkkkkkkkxxxxxxxxxxxddddddoooollllllollllllcccc;,,'',,,,,;;:cldddxdxdddddxxxxxx
XXXXXXXXXXXXK000KK000KKXXXXXNXXXXNNNNNXOdox0NNNNNNNNXXXNNNNXXKXXK00KKKKXXNNNNNNNNNNNNNNNNNNNNNNNNXKXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXNNXXXNNXXXXXXXK00koc:;;::;;:coddddxxxxxxxxxxxkkkkkkkkkkkkkkkkkkxxxxdddddollc:::::::::::::clllllllccc:,''.'',,,,;:cloddxdxxxdddxxxxxd
XXXXXXXXKKXXK0KKKXXXXXXXXXXXNXXXXXNNNNXOolloddddxkkOOOOO000xoddxxkOOkxxxk0XNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXNXXXXXXXXXXXXKKOdcc:;;:;;;cloddddddoooooddddddddxxxxxkkkkkkkkxxdoolollc;,,''''''..''''''',;:clllllc:;'....',,,,;:lodddddddddxxxdxdd
XXKKKXXXKKXXXXXXXXXXXXXXXXXXNXXXXXXXNNKkoc::cc:,'''',:cc:,'...'';:lllc:;,:d0XXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXNNXXXXXXXXXXXKK0xlc:;,;;;;:lodddolc:::;;;;;,,,,;;:clodxxkkkkkkxxdolccc::;;;,,,,,,;;,,,,'''..',;:clccc;'....''',,;:coddddddxxxxxxdxxd
KK00KKXXXXXXXXXXXXXXXXXXNNXXXXXKKXKKKKOo:,;;;;::;'.....,lc'.   ...';,,,,...;dkOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXX0Oxoc;,,;,,;:lddo:;;;;;;;;;,,,,,,,,;:loddxxkkkkxxdddollllcccccclllooooollc:;;;;,,,;clcc:,.....'',,;;codddxxddoooodddo:
KKXXXXXXXXXXXXXXXXXXXXXXXXXXK0Okxxxdlc:,......,,'..... .';'.    .......,;'. .;:ccokKXXNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0kdl:,'''',;cool;;:clooddddoooolllloddddxkkOOkkxxdddollllooodddxxxddddddoooollcc:;;;cccc;'....''',,;codddooooodolcodoo
XXXXXXXXXXXXXXXXXXXXXXXXKK0xolc:c:;'..................   ...............''.. .',,';lk0KXNNNNNNNNNNNNNNNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0kdl:'....';lol:clodxxxxkxxxxdddoooddddxkkkOOkkxddoolcccloddxxxxxxdddoooooooollllc::cccc:,.....'''',:codoclddxxdlcoddd
XXXXXXXXXXXKKXXXXXXXXXK0Oo:,'................ ... ....    ..             ...........;llxKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK0xdl;'....,coolcoddxxxxxxxxxddoollllooddxxkkkkxddolc:;:clooddddooooollllllllllllllccclllc;........',::cllclodoolcodolo
XXXXXXXXXXKKXXK0KXXXK0xo:.................                                      .......:OXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKK0xdl;'....;odooodxddddddddooc::;;;::cloddxkkkxddolc:;;:clc:clc::,'',,,;;:::ccllllllllllllc'........,;::cloollllodddoll
XXXKKXKKKXXKK0O00KXXOocc:. ..       ....                 .                        .....'oKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKK0kdc,'...'lddoodxdddoolc:;;,'...',;;;coddxxxxxdoolc:;;::;,:looc:'..'''..',;::ccclllllllool;........',;cloddddddddddddd
KK000KKKKXXKKKKKKXX0o:;:;.           .....                                           ...,lxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKKKKKK0KKKKKK000KKKKK0Okxc,....;oddddxxddoc:,'';c:;,,;::cclodddxxxxdollccc:::::clllllc::;;;;;;,,;;:cclloooooooooc,.......',:lodddddddddddddd
000KKXXXXXXXXXKKOxdo,.........      .....                                               ...';ldO0KXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXKKKK000000OOO0000000000000Okko:;'.',cdxxxxxxdolccccllllclllllloodddxxxxxddolllcccc::ccllloooooooooollllllllooooooooool;......',;loodddddddddddddd
KXXXXXXXXXXXKKOdc.............                                                          ......,lx0XXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXKKKKKK0000OOOOOkkOOOOOOO000OOOOkkxlcc;',:oxxxxxxdddddddddxxdddddddddddxxxxxxxddoollcccccccclllooooddddddddddooooooooooooooo:'....'',:odddddddddddddddd
XXXXXXXXXKKKKOo,..     .. ....                                                          .......,lOKXXNNNNNNNNNNXXXXXXXXXXXXNNNNNNNNNNNXXXXXXXXXXXXKKKKKKK0000OOOkkkkkkkkkkkkOOOOOOOOOkkxoll:,,cdxxxxxxdxxxxxxxxxxxxdxxxxxxxxxxxxxxxdddoolccllllllllloooodddddddddddddddddoooooooo:,''''',,:odddddddddddddddd
XXXXXXXXXKXXKd'.....                         ......                                             .,lkKXNNNNNXXXXXXXXXXXXXXXXXXNNNNNNNNNNXXXXXXXXXKKKKK00000OOOOkkkkxxxxxxxkkkkkkkkkkOOkkdloo:',cxxxkxxxxxxxkkkxxxxxxxxxxxkkkkkxxxxxxxxxddollcclllllllooooddddddddddddddddddddddddoc;,,;;;;;:loddddddddddddddd
XXXXXXXXXXXXOc.... ..     .                  .  ....                                            ...:OXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNXXXXXXXKKKKK00000OOOkkkkxxxxxxxxxxxxxkkkkkkkkOkkdllc,.,lxkxxxxxxkkkkkxxxxxxxxxxxkkOkkxxkkOOkkkkxdoolcccclllloodddddddddddddddddddddddddddol:;;::;;;cloddddddddddddddd
XXXXXXK00000o'.....                                                                             ...,dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNXXXXXXXKKKK0000OOOOkkkxxxxxxxxxxxxxxxxxxxxxxkkkkkkdlc:,,lxkxxkkkkkkkkkkkxxxxxkkkkkkkkxxxkkOkkkkxddolllllllllodddxxxxxxxdddddddddddddddddddolc::c::::cllddddddddddddddd
XXXXXXKK0kxo,.                                                   .                                .'l0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK000OOOkkxxdxkOkkkkxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkxoc:lxkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxdddolcccclllccodxxkkkkkxxxxxxddddddddddddddddolccccc::clllodddddddddddddd
XXXXXKKKOxdc.          .    .......                              ..                                ..l0KXXXXXXXXXXXXXXKKKKKKKKKKKKKKK00000OOOOOOkkkdoxOkkxxxxxxxxxxxxxxxxxxxxxxxxxxkkOOOOOOkdclxkxkkkkkxkkkkkkkkkkkkkkkxxkkxxoccoxdddoc,',:cccccldkOOOkkkkkkxxxxxdddddddddddddddolcccc::cloooooddddddddddddd
XXXXXXKKOdlc'.               ..................                                                    ..,xKKXXKKKKKKKKKK000000KKKKKXXXXXXXXKKKK0000OOOxoxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxkkOOOOOOOkoldxkkkkkxxkkkkOOOOOkkkkkkxxxddodddxxxdollcc:ccccloxxkOOOOOOkkkkxxxxdddddddddddddddolccclcclooooooodddddddddddd
KKXKKKK0Oxc:;....           ....',,'.,;;,,,,'....                                                   .:k000KKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKK0000OOOOxoxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkOOOOOOxodxkkkkkkkkkOOOOOOOOkkkkkkkkxxxxxkkkxxxxxdolllllodxxkOOOOOOOkkkkxxxxddddddddddddddoc::cllloooooooooddddddddddd
0KXKKKKOo,.''.....          ...:cc:'';:ccccc::;,....     ....   .....   .                           .o0KXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKK00000OOOkkdoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkOOOkxxxkkkkkkkkOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkxddoooooddxxkkOOOOOOkkkkxxxdddddddddddddolc:clllloooooooooodddddddddd
KXXXKXXO:..........         ..',,,;,'';::cccccc:;,'........''''..............                       'dKXXXXXKXXXXXXXKKXXXXKKXKKXKKXK00000OOxdkOOkkkooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkOOOkkxxxkkkkxkkkOOOOOOOOOkkkOkkkkkkkkkkkkkkkOOkxxdddoooddxxxkOOOkkkkkkxxxdddddddddddddoollllllloooooooooooddddddddd
XXXXXKKOc.  .......        ..:oollloooooolllllllllc:;,,,;;:::::;;;,,,,,,,''....                    .,xKXXXXK0K0kkkK0kkOxOOk00xkOxdkxkKOkkOkxddkkkkxooxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkOOkkxxxxkkkkkkkOOOOOOOOOOOOOOOkkkkkOOkkkkkkkkkkxxxddddodddxxxkkkkkkkkxxxxdddooodddddddodoolllcllooooooooooddddddddd
0KXXXK0xl,. .....          .'cdxkkkkkkkkkxxxdddddooolllllllcc:::::::;;;;;,,,'...                    .:kKXXXK00kdxk0OkOxk0OKKOxkOxk0kOKOdxOxdxkOkkxxooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkxxxkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOkkxxxxxxxddooodddddddddxxxxkkkkkxxxxxddoooooddddddoddooolcclloooooooooddddddddd
0KXXXX0xc:'.......        ..;lxkkkkkkkkkkxxxxddddoooooooollcccccccc::::::;;;,,'..                  ..,lOKXXK0KK0K00kOKO0K0KKOkO000K00K0kO0OkkOOkkxxooxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkxxkkkOkkkkkkkOOOOOOOOOOOOOOOOOOkxxdddddoooollllllloooddddxxxxxxkkxxxxxdddooooooooooooooooollclloooooooooodddddddd
KKKXXXKOo;........       ..':oxkkkkkkkkkxxxxxddoooooooooollllllccccc::::::::;,'..                  .';oOXXXXXXXXXXXKKXXXXXXXXXKKKKKKKK00000OOOkkxxxooxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkOOkkxxOOkkkkkkkkkkOOOOOOOOOOkkkkkxdollclllllcclcccc::::::::cclodxxxxxkxxxxxdddooooooooooolloooolllclloooollooooddddddd
XXXXXXKK0o..         ......:ldxkkkkkkkkkxxxxxddooooooooolllllllccccc:::::::::;,..                  .'cd0KXXXXXXXXXXXXXXXXXXXXXXXXKKKK00000OOOkkxxxdodxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkOOOOOkkOOOkkkkkkkkkkOOOOOOOOkkxollllllllloooollloollllccc:::::::codxxxxxxxxxxdddoooooooool::clloollllllllooolllooodddddd
XXXXXXXX0x:.        ......:oxxkkkkkkkkkkxxxxxddoooooollllllllllccccccc:::::::;,..                   'lx0XXXXXXXXXXXXXXXXKKKKKK0000OOOOOOkkkkxxxddoooxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOOkkkxxxxkkkkOOOOOOOOkxdoodddddddddddddddoooooollllooooooooodxxkxxxxxdddoooooooool,..,;::cccllllllllllllloooodddd
XXXXXXXXKOd'.      ......;ldxxkkkkkkkkkkkkxxxddddoooollllolllllcccccccc::::::;'..                   .ck00KKKKKK00K000KK00KK00KKKK0000000000OOkkkxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkOOO0OOOOOOkOO0OOkkxkkkOOOOOOOOOOkkkkkOOOkkkkkxxxddddddxxddddddddoooooooxkkxxxxddddooooooool;....',;;:cccllllclloolloooooooo
XXXXXXXXX0xc..     .   .,cdxxxxxkkkkkkkkkkkxxxxxddoooooooooolllcccccccc::::::;,..                  .;x0KKKKKXXXXXXK0KXXXXXXXXXXXXKKKKKK0000OOkkkxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkOOOOO000OOOOOO00000OkdxkkkOOOOOOOOOOOOOOOOOOOOOOkkxxxxxkkkkxxxdddddddddooodxxxxxxdddoooooooolc.  ....',;;::ccccccllllllooooooo
KXXXXXXXXKOc....   .  ..cdxxxxxxdoddxxkkkkkkxxxxdddddoooooolllllccccccc::::::;,'.                 .cOKXXXXXXXXXXXXXKKKXXXXXXXXXXKKKKKKK0000OOkkkxxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOO0000OOOO000000OkxoldkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkxxxddddddddooddxxxxddddoooooollll,.     ...'',;:::cccccllllloooooo
KKXXXXXXKK0l..........'lxxxdoc:;;,',,;::clodxxxxddddollloolllccccc:::;;;;::::;;,.                .o0KXXXXXXXXXXXXXXXKKKXXXXXXXXXKKKKKKKK000OOOkkxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOO000OOO0KKK0OOOkxo;:dkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxxxddddoooodddddddoooooolllll:'         ...',;::ccclclllloooooo
KKXXXXXXXXKx,........'cxxxxdlcccc:;;,''...',;cloooooolllllc:;,''..........',;;;;,.              .cOKXXXXXXXXXXXXXXXXXXKKXXXXXXXXKKKKKKKK000OOOkkxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOO0000OO00KKK00OOOkxl;';okkkOOOOOOOOOOOOOOOOOOOOOkkkkkxxxxxxxxxxxdddooooooddddooooolllllllc:.            ..',;::clllllllloooo
KKXXXXXXXXXKkc,......;oxxxxxxxddolcc;,''''',;:cloooollccc:,'..................,;;,'.            'dKXXXXXXXXXXXXXXXXXXXXK00KXXXXKKKKKK0000OOOOkkkkxkkkxxxkkkkkkkkkkkkkOOOOOOOOOOOO000000KKKKK0OO0Oxol;'',lxkkkOOOOOOOOOOOOOOOOOOOOkkkkkkxxxxxxxddddoooooooooooooolllllllccc;.           .....',;:cccccllllloo
KKKXXXXXXXXXXKOdc,'..cxxkkxxdoc:;:lo:.. .',',clodxdolcc:,'...........'''''...',;;;;,.          .:kKXXXXXXXXXXXXXXXXXXXXXKOKXKK0000KK00000OOOOkkxxxxxkkkkkkkkkkkkkkkkkOOOOOOOOOOOO00000KKKKKK0OOOOxoc;,,,,:oxkkkOOOOOOOOOOOOOOOOOOOkkkkkkkkxxdddddoooooooooooolllllllcccccc;.          ........,;:cccllllllll
KXXXXXXXXXXXXXXKxol;,oxxkkkxdolcloxxc,..';;,,codxkxdoc:,......',:,.   ......'',;;;;;'       ..';d0XXXXXXXXXXXXXXXXXXXXXXKKKKXXXXXXXXXKKKK0000OOkkxxxxxxxkkkkkkkkkkkkOOOOOOOOOOO0000000KKKKK00OOOkxlc;,,,,'.;lxkkkOOOOOOOOOO0000OOkkkkkkkkkxxddddooooooooollllllccccccccccc;.    .... ..........';::cllllllll
KKKKKKKKXXXXXXXKOdo::oxxkkkxxxdddddolc:;;;;;clddxxxdlc:,......';:;.  .''.....',;;::;'.     .'cdk0XXXXXXXXXXXXXXXXXXXXXXXKK0KXKXNXXXXXKKKK0000OOOkkkkxxxxxxkkkkkkkkOOOOOOOOOOOOO000KKKKKKKXK000OOkdlc;,'''...';ldxxkkkOOOOOOO00OOOOkkkkkkkkxxddoooooollllllccccc:::cccccccc;..   ...........'...',;::ccllllll
KKK0KXXXXXNNNNNXOdl:cdxxkkxxxxxxxxddollccccloddxxxdolc:;,'.''''',,'''''''''',,;;:::;,.    ..cOKXXXXXXXXXXXXXXXXXXXXXXXXKKK0KKKXNNNXXXXKKKK0000OOOkkkkkkkxxxkkkOOOOOOOOOOOOOOOO000KKKKKKKKK00K0OOxolc:'......,,,cdxxxxkkkOOOOOOOOOkkkkkkkkkxxdoollllllccccc:::::::::cccccc:;..   ..........',''',,;;:::ccllll
KKKKXXNNNNNNNNNN0kdlldxxxxkxkkkxxxxdddoooodddxxxxddolc:;,,'',,,,,,,,,,,,,;;;::::::::,.....':xKXXXXXXXXXXXXXXXXXXXXXXXXKKXKKKKKKKXXKXXKKKK0000OOOOkkxxxkkkkxxkOOOOOOOOOOOOOOOO000KKKKKXKKK00KKK0Oxocc:.......,,,:dkxxxxxxxkkkkkkkkkkxkkkkkxxdoollcccc:::::::::::::::cccccc:;'.       .....''','',,;;;:::ccccc
XXXKKKXXXNNNNNNNXOkxddxxxkkkkkkxxxddddddddddxxxxxdolc::;;,,,;;;;;;;;;;;:::::::::::::;....,l0XXXXXXXXXXXXXXXXXXXXXXXXXXKKXKXK00K0KK0KKOOOOk0KkdkkxxxdxxkkkkkxkOOOOOOOOOOOOOOOO000KKKKXXXKKKKKXK0Oxoc;,.........''lkkkxxxxxxxxxxxxxxxdxxxxxdoolcc:::::;;;;;;:::::::::cccccc::,.       .....''.''',,,;;;:::cccc
KKXKKKKKKXNNNXXNNXOkxxxxkkkkkkkkxxddddddddxxxxxxddolc::;;,,,;;:::::::::::::::::::;;:,''',:xKXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXXKKK0XXO0KOO00OK0xOOdxkkddkkkkOOxxOOOOOOOOOOOOO000000KKKKXXXXXXXXXK0kol:'...    .....;xkkkxxxxxxdddooooooooolllcc:::;;;;;;;;;;:::::::::ccccccc::;'         ..''...'''',,;;;::::cc
KKXXXXXXXXNNNXNWNNXOxxxkkkkkkkkkxxxxddddddxxxxxddollc:::;,,,;;;:::::::::::::::::;;;;,,;;:oOXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKXXNNNNNXXXXXXX00K0O00kkOkxxkkkkOkxkOOOOOOOOOO000000000KKKXXXXXXKXXK0koc;...         ...okkkkkkxxxxxxdooollllcccc::::;;;;;;;;;;;::::::cccccccccc::;,.        ..''.....''',,;;;:::::
KKXXNNNNNNWWWWWWWWWX0kxkkkkkkkkkkxxxxddoooddddxddollc:::;,,',;;::::::::::::;;;;;;;;;;::cxKXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXNNNNNXXXXKKKKK00000OOkkkkkkkkOOOOOOO000000000000KKKKXXXXXK00Oxo:,....          ...:xkkkkkkkkxxxxxxddooolllccc::::::::::::::::cccllllllllcc:::;.       ............'',,,;;;:::
XXXXXXNNNNNNNNNNNWWWN0xkkkkkkkkkkkxxdoooodddxxxxdoolc::;;;,'.';::::::::::::;;;;;;;;;;cokKXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK00000OOOOkkkkkOOOOOOOO0000000000000KKKKKXKKK0Oxdl:,'....          ....,dkkOkkkkkkxxxxxxxdddooollllccccc:::::::cclllllooolllllc::;;'.       ............',',,;;;::
XXNNNNNNNNNWWWWWWWWWWKxkkkkkkkkkkxxdollodxxxxxxxddolc:;;;;;,..,;::::::::;;;;;;;;;;::cdOXNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNXXXXKKKKKK000000OOOOOOOOOOOOOO000000000KKKKKKKKKK0Okxol:;,,'....    ....  .... .okkkkkkkkkkkxxxxxxddddooollllllcccccccclllooooooooolllcc:;,'.       ............'''',,,;;;
XXXNNNNNWWWWWWWWWWWWWXkxkkkkkkkkxdolclodxxdoodddoolc;,''',,,'',::::::::;;;;;;;;;;;;:okKXNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNXXXXXXKKKKK0000OOOOOOOOOOOO0000000KK0KK000KKKOkdlc:;,,''''.....   .''.. ....  'okkkOOOOkkkkkxxxxxxddddooooolllllllllllooooooooooooollcc:;,'..    ..............''''',,,;;
XXXNNNNNWWWWWWWWWWWWWXOkkkkkkkkkxdooodxxxxxddddoolc:,'...',,;;::ccc::::;;;;;;;;;;cdkKXNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNXXXXXKKKKKK00000OOOOOOOOOOOO0000000000000000koc:,,',;;:cc:,'....  ..''... ..  .:dkkOOOOOOOOkkkkkxxxxxddddoooooooooooooooooddddddoooollc:;,,'... .....................',,,,
XXXXNXXNNNNNWWWWWNNNNN0kkkkkkkkxxddddxxxxxxxxxddollc;,,',;;::::::ccc::;;;;;;;;,,:xXNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNXXXKKXKKKKK00000OOOOOOOOOOOOO00000000000OOOxl;,,,;:clllc:,........ ..'''...    .cdkkOOOOOOOOOOkkkkkkxxxxxddddddddoooooooddddxxddddooollc:;,''..........................,,,,
XXXXXXKKXNNNNNNNNNXNNNKkxkkkkkkxxxdddxxkkxxxxxdolcllc::;;;;;;;;:::::::;;;,,,,,,;;cox0XNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK0KKK0000OO0OOOOOkkOOOOOOOOO00000000Okxdl,...',;;;'......... ...  ..''...    .cdkkOOOOOOOOOOOkkkkkkkkxxxxxxdddddddddddxxxxxxxdddooollc:;,'''............................'
XXXXXKKKXXXXXXXNNXXXXXXOxkkkkkkkxddollooooooooollccc::;;;;,,;,,;;;::;;;;;,,,,,,'. ..,cdOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK00K0OO00kkOOOOkkOOOOOOOOOOOOOkkxdolc:;,..................   ...  ..'''...   .;oxkOOOOOOOOOOOOkkkkkkkkkxxxxxxddddddxxxkkkkkxxxddooollc:;;,''.............................
XKKXXKKXXXXXXXXXXXXXXXXKOxkkkkxxxdoc::::cc::::::::;,,''.......',;::;;;;,,,,,,,,.    ...;o0XXXXXXXXXXXXXXXXXXXXXXXXXKKKXKKKKKKKKKKOO0OOOOOkOOkkOOkkkOkOOOOkdl:;;,,,'................. ........    ..  ..','...   ..:dkkOOOOOOOOOOOkkkkkkkkkkkxxxxxddddxxkkkkkkkkxxddoollcc:;;;'..............................
KK0KXKKKKKXXXXXXXXXXXXXXKkxkkxxxxdooodollllc::;;;,,,''........';;;;;;;,,,,,'',,.     ...':dO000KXXXXXXXXXXKKKKKKKKK0OKKKKKKKKK000OOOkkxdxddxxxxdxkxxxxxdl;.......................   ........'..  .   ..''''...   .':dkkOOOOOOOOOOOOOOkkkkkkkkxxxxxxxxkkkOOOOkkkxxddolllcc::;,'..............................
KKKKXKXK0000KKKKKXXXXXXXXKkxxxxxxxxxxxxxddoollcc::::;;,''''''',;;;;;,,,,''''','.      ...';:cccldxkOKXXXXKKKKKKKKK0OkOKKK00000OOOkkkxdddolodxxllddc:,'.....  ................       ........,'.       ..''''...   .,:oxkkOOOOOOOOOOOOOOOOkkkkkkkkxxkkkkOOOOkkkkxxdoollcc:;,'................................
XXXXXKKKKXK0KKKKXXXXXXXXKkoldxxxxxxxxxxxxxdoolccc:::;;,'''',,,;;;;;,,,''''.'',,.     .....',;;,,'',;:ldxOXXXXXXXXKKOk0K0000OOOOkkkxkxxxxxddxkkdol:'........ ..............         .....   .',..      ..'''''...  ..,;lxkkOOOOOOOOOOOOOOOkkkkkkkkkkkkkOOOOOkkkxxddooolc;'............................       
XXXXKKXXXXXXXXXXXXXX0xo:'.':ldxxxxxxxxxxxxddollllcccc::;,,,,,,;;,,,''''....'',,.     .....'',,''''...'',:lxOKXXXKKK000000OOOOkkxxxxxdddxxxxkkdl;'......................           ....      .,'..    ....'''.....  ..,:lxkOOOOOOOOOOOOOOOkkkkkkkkkkkOOOOOOOkkxxxddooo:,...........................          
XXXXXXXKKXXXXXNXKko;.   .;:;,;cdxxxxxxxxxxxddooolllccc::;;;,,,,,,,''......'',,''.     .....',,,','.    ....,:oxO0KK00000OOOkkkxxddddddddoodl:,.....................             ....        .',,..      .........   ..,:oxkOOOOOOOOOOOOOOOOOkkkkkkkOOOOOOOkkkxxddddl,........................               
XXXXXXXXXXXK0kd:'.   ..;:;,'..'oxxxxxxxxxxxxdddooolcc::::;;;,,,,''.......'',,,''.     .....'',,,,,''.....     ..,cdkO00OOOkkkxxdddddddol:,'...... .......    ..                ...           .,,'..       .......   ...,:lxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxdddl:,.....................                   
XXXXXXXKOxo:'.     ..;::;'... ,dkxxxxxxxxxxxxdddoolc::::;;;,,,''.......'',,,,,''.      ..''''','..',,,;,,''...    ...;lkOkkkxxdddddolc;'........  .......                   ....             ......        ......    ..'',coxOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxd:''''...................                    
KXXXKOdc,..       .,::;,.... .cxkkkxxxxxxxddddooollc:::;;,,,''......'',,;;,,,,,,..     .,,,'''''..'''''''',,,,'..     .,coxxxdddddoc,..........  ....                      ....  .          .......        ......    ..''',:ldxkOOOOOOOOOOOOOOOOOOOOOOOOkxlllol;'''.....................                    
KKKko:'.       ...;:;,'...   'dkkkOOkxdddddddooolllcc:;,,''''''',,;;;;;;;;;,,,,,'.     .;:;,'''....'.''...''''''''..    ..,coddodo:...........   .... .                  ..........        ........        ......    ..','',:ccodxkkOOOOOOOOOOOOOOOOOOOxl'...............................  .                
0kl;..       ...':c;'....   .;dkkkkOOOOkxdoollllllcc:;,''',;;:::ccc::::;;;;;,,,,'..    .:c:;'''.............''''''''..    ..,cooc,.  .........  ....     ..              ..........        ..... .. .      ......    ..',,,,;::cclodxkkkkOOOOOOOOOOOOOxc'.      .........................  .                
:'.        ....;::;'.. .    .:dkkkkkOOOOOkxxdooollcc:::::ccccllcccc:::::;;;;,,,,,.     .:c:;,''.............'''',,,,,'..   ..';:..    ........ ....     ....          ..    .........      .......  ..  ..  .....     ..',,,,;:::::cclodxxkkkkkkkkkkkxc..       .......................   ..                
         ....';:;,'.  .    .,:oxkkkkOOOOOOOkkkxxxddooollllllllllccccc:::;;;;;;,;,.     .;c:;,''............'',,,,,,,,,'..   .....      ...........      ....       .....       ......... .........   .. ...  .....   ...',,,,;;::::::::cclloddxxxxdl:,.        ....................      ...                
       .....,::;,..       .';:lxkkkOOOOOOOOOkkkxxxddooooooddoolcccccc:::::;;;;;;,.     .;c:;,''.........''',,;;;;;;;,,,''..   ...       .........       ....     ......          ..................   ..  .  .....   ...'',,,,,,;;;;:::::::cc::;;'....        ...................      .....                
     ......,::;'.    .    .,;:cdxkOOOOOOOOOOkkkxxxxddddddxxddolccccccccc:::::::;'      .;cc;,''........'',,;;;:;;;;;,,,''...  ..        ........       .....     .......           .................. ...    .....   ....',,,,,,'''''''''''..........        ..................      .......                
.........',;:;'.    .   ...,::cldkOOOOO00OOOOkkkxxxxxxxxxxxdollcccllllccccccccc;.      .;cc:;''.......'',,;;:;;::;;;,,,,'...       .     .......      .....          ...              ...................     ....    ...''',,,,''''................          ..............      .........                 
........';::,..    ..  ...';:::cdkOOOOO00OOOOOOkkkkkkkkkkxdollllllooolllllllcl:.       .:c::;'........',,;:::;;:;;;;,,'''...       .     ......      ......         .....              ......... ....... .    ....    ...'''''',''''...............          .............     ..........                   
.......';::,..    .......',;::cldkkOOO0000OOOOOOOOOOOOOkxxdollllooddoooolllll:.        .:c:;,'........';:::::::::::;,,''...   .     .    .....       .....         .......               .......  .......     ....    ...',,,'''''''..............         ...........     .............                    
......';:;'.............',;:cccldxkkOO0000OOOOOOOOOOOOOkxddoollooooooooolllc'.        .'cc:;,'.......',;::::::::::;,,''....   .     .     ....       .....         ........                 .....  ......      ...     ..',,,,''''''.............       ...........     ............                        
.....,;:;...............',;:ccloxkkkOOO000OOOOOO00000OOkxxdoooooooooooool:'.          .'cc:;''.......,;:::c:::::::;,''.....   ..          ...       .....         .........               .....  .  ......     ...     ..',,''''''''...........      ...........     ...........                            
....,::,...'.............',:clldxkOOOOOOOOOOOOOO0000OOOOkkxddddddddddol;.             .,c::,'.......';:::::::::::;,,'.....     .          ...       .....       ..........                 ........  ......     ..     ...,,'''''''''.......       ..........    ...............                            
..',;;''',,...............',:cloxkOOOOOOOOOOOOOOOOOOOOkOOkkxxxxxdddoc,.               .;c:;,'.......,::::::::;,...''......    ...         ...       .....      ..........     ....          ........   ....             ..',''''''''.......      ............................ ..                            
.',,,',:;..................'';:loxkkOkkOOOOOOOOOOOOOOkOOkkkkxxxxdl;..                ..;c;,,.......,;::::::,....  .    ...    ....         .        ....      ..........     .......         .......     ....           ...,'''',''.....       ....... ...................                                 .
',,;;;,,,.....................,;codxkkkkkOOOOOOOOOOOOOOOkkkkxdc;'.         .         .';:;,'......,;:::::;'. ..       ....    ....    .    .        ....     ..........      ..........   ...  .....       ...           ..''...''....     ............................                                   ..
,,;:;,..........................';:lodxkkkkOOOOOOOOOOOOOkxoc,......      ..          .';:,'......,::c:::,.......     .....    .....       ..        ....     ..........    .............. ...     .          ..          ..'''.......     .....  ...................                                      ..
;::,'..   .........................';:clodxxxxxxxxxdolc:;,.........   ....          .'.,;,'.....,;:cc::,..,,'.............     .....      .         ....    ..........    ......... .......                    .          .'''.....      ....................                                            .. 
:;,'..   .............................''',,,,,,,''.......................         .','.',,'....';:::::,..''..''..........      ......   ...         ....   ..........   ......................                           ...''...      .......   . ....                                                ..   
:;'..   ................................................................         .':;...',...',;::c::;..'..''............      ......   ...         ...   ................................... ..                          ..''..   ...                                                                     .
,'..   .................................................................         '::,....'''',;::cc:;.....................      .. ...   ..        .... .....................................                             .......                                                                      .....
'.     ................................................................         .;c;,'....'',,;;cc::,.....................      .. ........        ..........................................                  .           .....                                                           ... .............
    )";
    cout << edpic;
}

void geo() {
    string sad = R"(ooodddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxdddooolllccc::::;;;;;;;;;;:::::ccccccccccccccc::::;;;,,,,'''''''''',,,,;;;;;::::::cccc:::::::;;;;;,,,''''.................................''',,,;
oooddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkxkkkkkkkkkkkkkkkkkxxxxxxxxxxxdddooollllcccc::::::;;;::::cccccclllllllllllccccc:::;;;,,,,,,,,,,,,,,,;;;::::ccccccccccccccc:::::;;;,,,,'''.........              .........''',,,
ooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkxxxxkkkkkkxxxxxkkkkkxxxxxxxxxxxdddooolllllcccc::::::::::cccclllllllllllolllllcccc:::;;;,,,,,,,,,,,,;;;::::cccclllllllllllcccccc::::;;;;,,'''........              .........''',,
ooodddddddddddxdddddddddddddddddddddddddddddddxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkxxkkkkkkkkkkkxkkkkkkxxkxxxxxxxdddoooolllllccccccc::::ccccclllllloooooooolllllccc:::;;;,,,,,,,,,,,;;;;:::cccllllllllllllllllcccccc::::;;,,,'''.......             ........''',,,
ooodddddddddddxxxxdddddddddddddddddddddddddddddxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxxkkkkxxxxxxxxxxdddoooolllllcccccccccccccclllllllooooollllllllcccc::;;;;,,,,,,,,,,,;;;::::ccclllllloooolllllllllcccc::::;;,,,'''.......          .........'',,,;;
ooodddddddddddxxxxddddddddddddddddddddddddddddxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkxxxkkkkkkkkkkkkkkkxkkkkkkkkkkxxxxxxddddoooollllccccccccccccccllllllllllllllllllcccc:::;;;;,,,,,,,,,,,,,;;;::::ccccllllllooooooollllllccccc:::;;,,,'''......        ........''',,;;;;
ooodddddddddddxxxxdddddddddddddddddddddddddddxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddddooooollllllllcccccccclllllllllllllllllcccc::::;;;,,,,,,,,,',,,,,,,;;;::::ccccllllllllloooollllllcccc:::;;;,,'''.......    ........''',,;;;:::
ooodddddddddddxxdddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkxxxkkkkkkkkkkkkkkkkkkkkkxxxxxxdddddooolllllllccccccccccclllllllllllllccccc::::;;;,,,,''''''''''',,,,,;;;;:::ccccclllllllllllolllllllccc:::;;;,,''..................'',,,;;::::c
oooddddddddddddddxxddddddddddddddddddddddddddxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkxxxxxxxxkkkkkkkkkkkkkkkxxxxxxddddddoollllllllllccccccllllllllllcccccccc::::;;;,,,,''''''''''''''',,,,;;;;;::::cccccclllllllllllllllcccc:::;;,,,''...............''',,,;;:::ccc
oooddddddddddxxxxxxddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxddddddddddddddddddxxxxxdddddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkxxkkkkkkxxxxxxxxxxxxxddxxxxddddddollllllllllllllllllccccc:::::;;;;,,,''''............''''',,,,;;;;:::::cccccccllllllllllllcccc:::;;,,'''.............''',,,;;:::cccc
oooddddddddddxxxxxxddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkxxxxxxkkkkkkkkOOOOOOOOO00000000000OOOOOkkxddolllccccccccc::::;;;;,,,,''''..................'''',,,,;;;;::::::cccccccllllllllccccc::;;;,,''.............'',,;;;:::ccccc
oooddddddddddxxxxxxdddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOO000000000000KKKK000000000000000000OOkxxdolc::::;;;;,,''''''......................''''',,,,;;;;;:::::ccccccllllllcccccc::;;,,,''...........'',,,;;:::cccccc
ooodddddddddddxddxdddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxddxxxxxxxxxxxxxddddddddxxxxxxxxxxxxxxxxxxkkkkkkxkkkkkkkxxkkkkkkkOOOOO00000000000000KK0000KK0000000000000KKKKKKKKKKKK0Okdolc;,,'.................................''''',,,,;;;;:::::cccccllllcccccc:::;;,,'''.........'',,,;;;::ccccccc
oooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkxxkkkkkOOOOOOOO0000000KKKKKKKK000000000000000000000KKKKKKKKKKKKKKKXXKK0kxdl:,'..................................''''',,,;;;;::::cccccllcccccc:::;;,,,'''......''',,,;;:::cccccccc
ooooddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxddddddddddddddddxxxxxxxxxxxkkkxxxxxxxxkkkkkkkkOOOOOO000000000000000000000000000000000KKKKKXXXXXXXXXXXXXXXXXXXXXXXK00Oxl:,..........       .................'''',,;;;;:::ccccccccccccc::;;;,,'''''''''''',,;;;::ccccccccc
ooooddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddxxdxxxxxxxxkxxxxxxxkkkkkkkkkkOOOOOO00000000000000000000000000KKKKKKKKXXXXXNNNNNWWNNNNNNNNNNNNNNNXXXXXXXK0kdc'.  ..            ................'',,,;;::::cccccccccccc:::;;,,,''''''''',,,;;;:::ccccccccc
ooooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddooddxxxxxxxddxxxxxxxxxxxkkkkxkkkkkkOOOOOOOOOOO0000000000000000KKK00KKKKKKKXXXXNNNNNNNWWWWWWWWWWWWWWWWWWWWNNXXXXXXXXK0xl;..  ......            .........'',,;;;:::ccccccccccc::::;;,,,,''''''',,,,;;;::cccccccccc
ooooodddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddoooooooooddxxxxxdddddxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOO0000000000000KKKKKKKKXXXXXXXXNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWNNXXXXKKKXKKKko;............ ... .    ......'',,;;;;:::ccccccccccc:::;;,,,,,,,,,,,,,,;;;:::cccccccccc
ooooodddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxdddddxxxxxxxxddddooollllloooddxxxxddxxxddxxxxxxkkkkkkkkkkkkkkkkkkOOOOOOOOO00000000000KKKKKKKXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNNNNXXXKKKKKKK0ko;'.......................''',,;;;:::cccccccccccc:::;;;,,,,,,,,,,,,;;;:::cccccclllcc
ooooodddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxddxxxddxxxxxddooollccclloodxxxxxxxddooddxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOO000000KKKKKXXXXXXNNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNNXXXXKKKKKKKK0kl;'...................'',,,;;;::::cccccccccccc:::;;;,,,,,,,,,,,;;;;:::cccclllllcc
ooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxdoollcccccclloooddddddddddddddxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOO000000KKKKXXXXXXXXNXXXXXNNNNNXNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNWNNNNXXXXXXKKKKKKKKK0xl;''''''''''''''''',,,,;;;:::cccccccccccccc:::;;;;,,,,,,,,,,;;;;:::cccclllllcc
ooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddxdddoolc:::::cccclloooooodddxxxxdddxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOO000000KKKKKKXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNXXXNNNXXXXXXXXXNNNNNNXXXXXXKKKKKKKKKKK0Odc;',,,,,,,,,,,,,,;;;;:::ccccccllllcccccc:::;;;;,,,,,,,,,;;;;;::cccccllllccc
oooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoolcc:;;;::::ccllloooooooodddddddddxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOO0000KKKKKKKKKKXXXXXXXXXXXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK000KK0xl;,,;;;;;;;;;;;;::::cccccccllllllccccc:::;;;;,,,,,,,,,;;;;:::cccclllllccc
oooddddddddddddxddddddddddddddddddddddddddddddddddddddddddddddddddddolc:;;;,,;;;::::clllllooodddddddddddxxkkkkkkkkkkkkkkxxxxkkkkkkkkkkkOOO00000KKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKK00KK0xl:;;::::::::::cccccccccllllllllccccc:::;;;,,,,,,,,,,;;;;:::cccclllllccc
ooodddddddddddxxdddddddddddddddddddddddddddddddddddddddddddddddddddol:;;;;;;;;;;::::ccllloooooddddxxxxxxxxkkkkkkkkkkkkkkxxxxkkkkkkkkkkkOO00000KK00000KKKKKKKKKKKXXXXXXXKKKXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXXXXXXXKKKKKKKKKKKKKKKK0000000xoc::ccccccccccccccllllllllllllcccc::;;;;,,,,,,,,,;;;;;:::ccclllllllcc
ooodddddddddddxxdddddddddddddddddddddddddddddddddddddddddddddddddolc:;,,,,,;;,,,;;;::cccllollooddddxxxxxxxxkkkkkkkkkkkxxxxxxxkkkkkkkkkkO0K0000KKK00000000KKKKKKKKKKXKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK00000000kolccccclccllllllllllllllllllccc:::;;;,,,,,,,,,,;;;;:::cccclllllllcc
ooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:;,,,,,,,''',,;;;;:ccllllloooddddxxxxxxxxkkkkkkkkxxxxxddxxxxkkkkkkkkO00000000000000000000000KKKKKKKKKKXXKKKKKKKKKKKKKKKKKXXKKKXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0KK00000000kollllllllllllllllooollllllccc:::;;,,,,,,,,,,,;;;;:::ccclllllllccc
oooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:,,,,,,,''''',,,;;::ccclloodddxxxxdddxxxxxxkkkkkkxxxxxddddxxxxkkkkkkkO00000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000K0Oxollllllooooooooooolllllcccc::;;,,,,,,,,,,,,;;;;:::cccllllllllcc
ooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol:;'',,'..'''''',,;;:ccclllooddddddoooodddddxkkkkkkxxxddooddxxkkkkkkkkOO0000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKKKKKKKKKKKKKKKKKK000KK0KK000Oxoooooooooooooooollllcccc::;;;,,,,,,,,,,,,;;;:::cccccllllllccc
oooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddolc;'',,''......''',;:::ccclllloollooddddddxxxxkkkxxxxxxdddddddxkkxxxxkkOOOO00000000000000000000000000K0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKKKKKKKKKKKKKKKKKKK00000000K0000Oxdoooooooooooooolllcccc::;;;,,,,'''',,,,,;;;:::cccccllllllccc
ooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddool:'.'''......''''',;::::::clcclloooooooodxxxxkkkxxxxxddddxdddddddxxxxxkOOOOOOOO00000OO000000OOO00000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXKKKKKKKKKKKKKKK00K0000000000000kdoooooooooolllllccc:::;;;,,,''''''',,,,,;;:::cccclllllllccc
oodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddol,..'......''''',,;;;;;;;;:cllooollooodddxxxxxxxxxddddddddddddddxxxxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOO000000000000K0KKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXKKXKKKKKKKK000KKKK0000000000000kxoooooooollllcccc:::;;;,,'''''''''',,,,;;:::cccclllllllccc
odddddddddddddddddddddddddddddddddddddddddddddddddddddddddoddl;'........''''',,,,,,,,;::ccllllloodddddddddxxxdddddddoddddddddxxdxxxkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOO000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKXXXKKKKKK0000KKKK0000000000000OOxollollllllcccc:::;;,,,'''''''''''',,,;;:::cccclllllllccc
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddoodo:'..........'''''''''',,;:cccccloooooollooddddddddddddddxxxxddddddddxxxkkxkkkOOOOOOOOOOOOOOOOOOOOOOOO00000000000KKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKKKKXXKKKKKKKK00KKKKK0000000000OOOOOxollllcccccc::;;;;,,''''......'''',,,;;:::cccllllllllccc
ddddddddddxddddddddddddddddddddddddddddddddddddddddddddddodoc,...................'',;::::cclooooooooodddddddddddddddxxxdddddoddddxxxkxxxkkkkkOOOkkkOOOOOOOOOOOOOOOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXKKKKKXXXKKKKKKKKKKKKKKKKKKK0000000OOO0Oxolccccc::::;;;,,,'''.........''',,,;;:::ccclllllllcccc
dddddddddxxxdddddddddddddddddddddddddddddddddddddddddddoodoc,....................'',;::cclllloooolooodddddddddddoooddddddddddddddxxkkxxxkkkkkkkkkkkkOOOOOOOOOOOOOOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOOOOOOkoc:::::;;;;,,,'''............'',,,;;:::ccclllllllcccc
ddddddddxxxxxdddddddddddddddddddddddddddddddddddddddddooool;....................'',;;::ccccllllcllooodddddddoooooooddddddddddddddxxxxxxxxkxkkkkkkkkkkkkkkkkkOOOOOOOO0000OOO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXKKKKKKKKKKKKK0000KK0000OOOOOOOOxlcc:;;;;,,''''..............''',,;;:::cccllllllllccc
dddddddxxxxxxxddddddddddddddddddddddddddddddddddddddddoooc;'....................',,;;;::::ccccllloooooddddddoooooooddddddddddddxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkOOOO00000000KK00KKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKXXKKKKKKKKKKK00KKK0000OOkkOkkkOxlcc:,''''''................''',,;;:::ccclllllllcccc
ddddddxxxxxxxddddddddddddddddddddddddddddddddddddddddoool:,....................',,;;;;;;::ccccloooooodddddddooooooooddoooddddddddxxxxxxxxxxkkkxxxxkkkkkkkkkkkkkkkkOOOO0000000KK000KKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKXXKKKKKKKKKKKKKKKK00000OOOOOkkOkdc;,;'''...................''',,;;:::ccclllllllcccc
ddddddxxxxxdddddddddddddooodddddddddddddddddddddddddooool:'..................''',;;;;;;;:::cloooooooodddddddollloooooooddddddddddxxxxxxxxxxxxxxxxxxkkkkkxxkkkkkkkOOOOOO00000000000KKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKK0000KKKKKKK00000OOOOkkkOko;;:,...........   .......''',,;;::cccclllllllcccc
ddddxxxxxxddddddddddddoooooooooodddddddddddddddddddooool:,..................'',,,,,,,,;:::clllllllloooooddddoolloooooloooddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOO00000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKK0000000OOOOOkOOko:;'.........      ......'',,;;;::cccclllllllcccc
ddxxxxxxxxddddddddddooooooooooooddddddddddddddddddddoooc;.................''''''',,,;::cclllcllllloooooooddddooooooolloooddddddddddddxxxxxxxxxxxxxxkkkkkkkxxkkkkkOOOOO000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK00KK0000000OkkkkOOxc,,''......       ......'',,,;;::ccccllllllllccc
xxxxxxxxxdddddddddoooooooooooooodddddddddddddddddddddolc,.....'''......''.'''''',;;:::ccccllllllllooooooooooooooooolloooodddddddddxxxxxxxxxxxxxxxxxkkxxxxxxxxkkkkOkkOOOO0000KKKKKKKKKKKKKKKKKKKKXXXXXKKKXXXXXXXXXXXXXXXXKKXXKKKKKKKKKKKKKKKKK0000000OOOkkkkkdc;,,,......     .......'',,,;;::ccccclllllllccc
xxxxdddddddddddddooooooooooooooodddddddddddddddddddddol:,...................'''',;;:::cllccccclloooooooooooooooooooolllloooddddddxxxxdxxxxxxxxxdddxkxdddxxxxxkkkkkkkkkOOO00000KKKKKKKKKKKKKKKKKKXXXXKXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOOkkkkkxo:;;;;,'...............'',,,;;::ccccclllllllccc
dddddddddddddddddooooooooooooooooddddddddddddddddddddooc,..........'''......',,;;;::cllcccccclllooooooooooooooooooolllllloodddddddxddddxxxxxxxxdddxxxxxxxxxxxxxxkkOOOkkO00000KKKKKKKKKKKKKKKKKKKXXXXXKKXXXKKXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOkkkkkkkdc;;,,,,''.............'',,,;;:::cccllllllllccc
dddddddddddddddooooooooooooooooooddddddddddddddddddddooc,'.........'.......',,,;::::cc::::cccllllooooooooooooddooolcccclllodddddddoooddxxdxxxxxxxdxxxxxxxxkkxxxkkkkkkkO00K00000KKKKKKKKKKKKKKKKXXXXKKKKKXKKKXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK000000000OOkkkkkkkkxoc:;,,,'''............'',,,;;:::cccllllllllccc
ddddddddddoooooooooooooooooooooooodddddddddddddddddddolc;,'...............',,,,;;;;;:ccccccclllloooooooooooooddddolccccclloooooddooooodxdddxxxxxddxxkkxxxxkkxxxxkkkkkOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKKKKKKKKKKKKKKK00000000OOOkkkkkkkkdlc::;,,'''...........'',,,;;:::cccllllllllccc
ddddddddoooooooooooooooooooooooooodddddddddddddddddoool:,,'............''''',,,;;;::cccccclooollllllooooodooddddddolcccccclloooooddddddxxxxxxxxxxxxkkkkxxxxxxxxxkkkkkkOO00000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKKKKK000KKKKKKKKKK000000000OOkkkxxkkkxolc::;,,,''..........''',,;;:::cccclllllllccc
ddddddoooooooooooooooooooooooooooooodddddddddddddooooll:;,''.............'',,,;;;:cllclllloooooolloooooddoodddddddoolccccccclooooddddddxxxxxxxxxxddxxxxxdddxxxxxxkkkkkkOOOO00000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKK00000KKKKKKKKKKKK00000000OOkkkkxkxxxdlccc:;,,,''........''',,,;;;::cccclllllllccc
ddddooooooooooooooooooooooooooooooooooddddddddodoooollc:,''.........''..'',,;;::cclllllllllllllooooooooooooodddddddollccccccllllooooooddddddxxxddddxxkkkxxxxxxxxkkkOOOOOO000000000KKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000KKKKKKKKKKKKKK0000000OOOkkkxkkxxdl:::::;,,,'''''....'''',,;;;:::ccclllllllccc
ooooooooooooooooooooooooooooooooooooooooooooddddooooll:;''........''''''',;;;:::cllllllccclllooooooolloodooodddddddoolcccccccllllloooodddddddxxxxxxxxxxxxxxxxxxkkkkOOOOOOO0000000000000000KKKKKKKKKKKKKKKKKK0KKKKKKKKKKKK00000000000K000KKK00000000OOOOkkkxxxxxddoc::::;,,,'''''''''''',,,;;:::cccclllllllcc
ooooooooooooooooooooooooooooooooooooooooooooooooooollc;,'.........''''',;;;:ccclcccccccclllllllolooooooodddddddddddoolccccc:cllllloddddddddddxxxxxxxxdddxxxxdxxxxxkkkOOOOOOO000000000000000000000000KKKKKKK000KKKKKK000000000000000000000000000000OOOOOkkkxxxxxddolc:;;;,,,''''..''''''',,;;;::ccccllllllllc
dddooooooooooooooooooooooooooooooooooodddooodoooooolc:;'......''..'''',::::c::ccllclllcccllcclllllooooooodddddddddddolccccccclllllloddoooddddddxxxxxxxxxxxxxxxxxxkkkkkkOOOO000OO00KK0KKKKKKKKKKK0000000000000KKKKKK00000000000000KKKKKK0000KK0000OOOOkkkkkxxxxxdddolc:;;;;,''''..''''''',,,;;:::ccclllllllll
ddddooooooooooooooooooooooooooooooooooddoooooooooooolc;'....''''....';::::::cllccccccccccllllllllllooooooddddddddxxxdolccccclllclllodddooododddxxxxxxxkkkxxkkkkkkkOOkkkOOOO000OOO000000KKKKKKKKKKKKKKKKK0KK00KKKKK0000000000KKKKK0000KK0000000000OOOOkkkkxxxxxxddoolc:;,;;;,''''.....'''',,;;;::ccccllllllll
ddddoooooooooooooooooooooooooooooooooododddoooooooollc,'''''''...'',;:;;;:cccc:::::ccclcllllccllllllooooooooddddxxxxxdollllllllllllodddooodddddddddddxxxxxxkkkkkkkOOOOOOOOOO00000000KKKKKKKKKKKKKKKKKKKKKK00000000000000000KKK0000KKKKKKKK00000000OOkkkkkxxxxxxxdlccc:;,,,;,''''......''',,,;;:::cccclllllll
ddddddooooooooooooooooooooooooooooooooddddoooodddoolc;,''''''...',;:::;;clccc:ccllllooollllcccllllllooooooodddddxxxxxddolooollllllllooooodddddddxdddddddddxxkkxxkkkOOOOOOOO0000000KKKKKKKKKKKKKKKKKKKKKKKKK00KKK0000000OO00000000000KKKKKKKKK0000OOkkkkkxxxxxxxxdlc::::,,,,,'''.........'',,;;;:::ccccllllll
dddddddddoooooodddooooooooooodddddddddddddddoddddooc;,'''.....',;:c:;;;ccc::cc:cclllccclllcccclllllloooooooddddddddddddooooolllllllooodddddddddxxddddxxxxxxxkkxxkkkkkOOOO0000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000KKKK000OOOOOOkkkxxxxxxddoc;;::;,,,,,'..........''',,;;:::ccccllllll
dddddddooooooooddoooooooooooddddddddddddddddddddddl:,'.''....,:::::;;:cc:::::;:cccc::::c::cccccllcclloooooodddddddooooooooooollllllloddoooddddddddddxxkkkxxxkkkkkkkkkkkkkOOO0000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000K0000000000OOOOOOOOOOkkxxxxxxddoc;;::;,,',,'...........'',,,;;:::cccllllll
dddoooooooooooooooooooddoodddddddddddddddddddddoolc;'.......';;;:::::cc:;:::::clc:::ccc::::ccccllccllooooooooodddoooddoolooooooooolloooolooodddodddddxxxdddxxxxxxxkkkkkkOO000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKK00KKK00000OOOOkkkOOkkxxxxxxxdoc:;;::,,''''............'',,,;;;::ccccllll
ooooooooooooooooooooooddoodddddddddddddddddddddoodol:'......,;;:c;,:ccc:;:::clcc::::::c::::ccccclllllooooooooddddoooddoollloooooooooooooooooooooooodddddxxxxxkkxxxxkkkkOOO00000KKKKKKKKKKKKKK0000KKKKKKKKKKKKK0000KKKK000000000KKKK0000000000000OOkkkkkkxxxxxxxxdoc:;;:;,''''..............'',,,;;;:::ccclll
oooooooooooooooooooooooooodddddddddddddddddollllodxkkxl;'..',,;::,';::;,,;;:cccc::;;:::::::::ccllccclooolooooddddoooddooooooooooloooooooodooooodddooddxxxxxxxkkkkkxkkkkOO0000000KKKKKKKKKKKKKKK00000000KKKKKKKKKKKKKKK0000000000KK0000000000000OOOOOOOkkxxxxkkxxdoc:;;:;,...................''',,;;;:::ccccl
oooooooooooooooooooooooooooddddddddddddddolccccccclodxxdc;'',,,;;'';::;,,;;:cc:::::::c::::::::clllcclloollooddddoooooooooooooooollloooddddddooddddooodddddxxxxxkkkkkkkkkO0000000KKKK000KKKKKKKKKKKKKK00K00000KKKKKKKKKKKKKKKKKKKKKKKKKK000000OOOOOOOOkkkkxxxxxxxddl;,;;;,.........    ........'',,,;;;:::ccc
ooooooooooooooooooooooooooooooddddddddddlc;;,,,;;:cclooool:,,,',;,';::;;;;;;:cc::c::::::::::::cccllcllloooooodddddoooooooooooooooooddddddxxxxxddddddddddooddxxxkkkkkkOOOOO000000KKKKK0KKKKKKKKKKKKKKKKKKKKKKK0KK0000KKKKKKKKKKKK00KKKKKKKK0K0O00OOOOkkkkkxxxxxxdddl;,,;;'.''......     ........''',,;;;;:::c
ooollooolllloooooooooooooooooooodddddddl:,........',:clllcc:;;;;;'';:;,',,,;::::::;;::::::::ccccclllooollooooodddooooddoooooooooooodddxddddxxxddddxddddddoooddxxxxxkkkkOOO000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKK000OOOOOOOO00000000KKKKKKKKKKKK0000OOOkkkkkxxxxxxxdddoc;,,,'........       .........''',,,;;;;:
llllllllllllllllllllooooooooooooooodddo:;'...........,:::::::::;;,,;;;''',,,;;;::;;;;;::::::ccclllcllllllooolloddooooooooooooddoooodddddddddddxxxxxxdddddddddddxxxxxxxxkkkkOOOOOO0KKKKKKKKXKKKKKKKKKKKKKKKKKKKK00000OOO00000000000KKKKKKKK000000OOOkkkOkkxxxxxxddool:;,,,'''... ...     ..........'''',,,,;;
lllllllllllllllllllllllooooooooooooodol:;,............,,;;::::;;,,,;;,'',,,,,;;;;;:::;;:::::ccclllccclllloooolooddoooooooddddxxdooodddddddddddddxxxxxxxxddddxxxxxkkkkkkkkkxkkkkkkOO0KK0KKKKKKKKXXKKKKK00KKKK00K00KKKKKKKKKKKKKKKKKKKKKK0000000OOOOOkkOkkxdxxxxxddol:::;,,,''........................''',,,,;
llllllllllllllllllllllllllllooooooooolc::,........'''',,,;;:::;;;;;;,,''''',,;;;:::;;::;;;::ccccccccclllllloooooddoooollllooooooooodddddddddddddddxxxkkkkkxdddddxxxxxxxkkkkkOOOOO0000000000KKKKKKKKKK000KKKK00KKKKKKKKKKKKKKKKKKKKKKKKKKK00000OOOkkkxkkkxxxdddoodol:;;;,,,,'........................'''',,,,
llllllllllllllllllllllllllllllooooooolcc:'.....';;,''..',;::::;;;;;,,,'...',;;::::;;;::;;;::cccccllllllllllloolodxxdddocccoooooooooddxkxxxxxddxxdddddxxxxxxxxxddddxxxxdxxxkkkkkOOO000KKKKKKKK000KKKKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000OOOkkxxkkkkxdddooddoc;,;;,,;,,'......................''''',,,
lllllllllllllllllllllllllllllllllloooc::;'....,;::;;,,,,,,,,;;;,,,,''''..',;::::::;;;;;::::::ccccllllllooolllllodxxxxxdolllodddooddxxkOOOOOOkkkOOkkkkkkkxxxkkkxxdddddxxxxxxxkkkkOkkO000KKKKKKKKKKKKKK0OOKKKKKK00KKKKKKK0000KKKKKKKKKKKKKKK00O00OOOOkkkkkkxxxddddddoc;,,,,,''''.....................''''''',,
llllllllllllllllllllllllllllllllllollc::,'',,,;::::;;;,'..',,,,;:;,''..'',,;::::::;,,;:::::ccccllllllllooollccccllooddooolloodddddddxxxxxxkkkkOOOOOOOOOOOOOOOOOkkxxxddddddddxxxkOOkOO000000KKKK0KKKKK0OOKKKKKKOOKKKKKKK0KKKKKKKKKKKKKKKKKK00OOOOkkkkkkkkxxddddddddoc:;,,''''''............'''''''''''''',,,,
llllllllllllllllllllllllllllllllllllc::;,',;;;::::::::;,...',',,;,,'..'',,,;:::;;;;;;;::ccclllllllllooloooollcccclloolooooooooodooodddddddooddxxkkkOOOOOOOOOOOOOO0OOkkkxxxdxxxxxOOkkO0000O000KK00000K0OOKKKKK0OOKK0000K000KK0KK0KKKKKKKKKK000OOOkkkkxxxxxdddddddddoc:::;,,,'''''''''''''''''',,,,,''',,,,,,,
llllllllllllllllllllllclllllllllllllccc;,,,;;::::::cclc:;,,,'''''''.'''.';;:::;;;;;::;;:cclllllolllllllllooollllcloddooooooooooollloooddxxxdddddxxkkkkkkkkOOO00OOOOOOOOOOOOOOkxxkOkO00OOOO000000O0000Oxk00KK0OO0KK0KKK0OO000000000000000OOOOOOkkOOOkxxddddddddddddocccc:;,,,,,,,,'',,,,,,,,,,,,,,,,,,,,,,,,,
llllllllllllllllllllllllllllllllllllc::;;,;;;::;;;:;:lolc;,'''..'''''''',;::;;,;::;;;:::clloooooooooooollooollllclodxxdolllooooollllcclodddddxxxxxxxkkkkxxxxxkkkkkOOOOOOOOOOkkkkOO00KK0OO0000K0OO0000OxxO00K0kk0KKKKKKOO0KKKKKKKK0000000OOOkkxxkkkkkxxddddddooodddlcccc:;;;;;;;,,,,,,,,;;;;;;;;;;;;;;;;;;;;;
llllllllllllllllllllllllllllccclllll:;:;;;;::::;;;,,,;::;,'.''..',,,,'',,;:;,;;:cc:;::::ccloooooooddddollooolllc:ccloolccclllllllccc:;;::cllllloooollllooddddddxxxxxxxxxxkkkxkkO00000000000OO000OOO00kxxkO00Oxx0KKKKK0O0KK0KK00000KK00000OOkkkkxxxxddddddddddooodoolcc:::::;:::::;;;;;;;;;;:::::::::::::;;;;
llllllllllllllllllllllllllllccclllll:::;,,;:::;;,,,'..''........''',;,,,,,,;::c:::;;;:::cccclloolooddddollloooolccclodolclllllllcccllcc:::ccccc::clllllllcccllllloodooddxxxxxxxxkkxxkkOOOOOOO00OOkkOOkddxO00kddO00000OO0K0000000000000OOOkkkkxxxkxxddoodddddddoddoolcc::::::::::::;;;;;:::::::::::::::::::::
lllllllllllllllllllllllllllllllcllllc:c:;,;::;;,,'''.....  ..''''''',,,;;,,;cc::;;,,;::ccccccllllooddddooooooooooccldddollllllcclllcc::c:::cc:::;;;;::cclolc::c::clooodddooooooddoooodxkxxkkkxxxxxkkkxodxOOOdodk0000OkO000000000000000Okkxkkkxxxxxxxxddddddddddddolclcc:::ccc:::::::::::::cccccccccccccccccc
llllllllllllllllllllllllllllllllllllc:c:;;:::;,,,,,,'..............',,;:;,;:clc:;,;;:::cccclllllloddddooddddollooolloooolcccllccccc:;;;;:;,,;;;;,,,'',,,,;ccc::;;;;:clllc:::::clooolloooolloooodxkxddxxkkkkdodkkkkkkkxkOOOO00000K00000Okkxxxkkkkxxddxxddddxddddddolclllcc:::::::::::::::cccccccccccccccccccc
llllllllllllllllllllllllllllllllllllc:::;;:::;,,,,,,'...   .......',,,,;;:clc:;,;;:::;;:cllllllloooodddooooddolc:cllolllllllcccc:;;;;,,,'..................',;;;;,,,;;:ccccc:::cccccccc:::cccodxddddxxddddolldkxddxkxodkOkkkO0O0000OOOOOkkkxddddxxddddddxxxdddoddolc:lllccc::::::::::::ccccccllllllllccccccc
llllllllllllllllllllllllllllllllllllc::;;;:ccc:,,,''...   ......,,,,,,;;:::;,'';;::;;:::cllllllllooooddddooloooolc::cccc:::cccc::;,''....    ........      .....'''''...',,;;,,,;,,,;;,,,;;;;:cllloollcloocclxkdlldxxccdkkdoxkkkkOOkxkkkkkOOkxxxxxxdxxkxxxxdddoddollccccc:::::::::::::ccccclllllllllllllllll
llllllllllllllllllllllllllllllllllllc:::;;:cllc:;,'.......','..,cc:;,,,;;;;''',,;;::;;:::cclllllllloooooddxdollodddolcccc:;;,,,;,'....................    .     ... ...    ..............''''',;::ccodxkxo::ldxdc:cdxo:coxocldxxddxxxxxkkkkkxxxkkxxxxkxxxxxdddodollllccc:::::;;:::::::ccccclllllllllllllllll
llllllllllllllllllllllllllllllllllllccc:,,:loolc:;,'';;;;;;,'',:cc:;,'',,;,,,;,,;:::;:::cccccllloooodollllooooooodxxxxdddddlcc::;,'''''',;:::;;;,..........   ......         ..................',:odddddolccclddl;,coo:;:ll::codooodxdddxxxkxxddxxxxkxxxkkxxddddlc:clccc::::;;:::::::cccccclllllllllllllllll
llllllllllllllllllllllllllllllllllllccc:,,;codoc:;;;:c:;,''..,cccc:;''',;;,,;;'';;:;;;::cclccccllllodxxdddollccccccllllllllc:;;;::::::cc;;cllllcc:;'.........''.....            .........'''',,,;ldxkOkkkxxdolodc'.';:;',;:;,;:ccllooolloooddoodddxxxxkkkkxxddxdl:::ccc::;;;;;;;:::::cccccclllllllllllllllll
lllllllllllllllllllllllllllllllllllllllc;',:lddoc::cllc;,'..':lcc::;,,,;,'',,,,;;;,,;:ccccclllllcccllooodddxxxddoooooolllloollllllloollol:cloooooolcc::::::;;;;,'...              .....,,,,',:ccllodxkOkkkkkdolc;........''...',,:clllccllllllllooodoodxxkkxddxo:;::ccc:;;;;;;;;;::::cccccllllllllllllllllll
lllllllllllllllllllllllllllllllllllllcll:'.,:cooollllllc:;,';lllc:;;,,;;,'',;,,,;;,,;:c:cc::clllllcccloooloooddddddxxxddooooooddxxddddooxdlcloooooolodddooolccc:;,,'...... ...........,:lc;,;:codxxkkxxxdddxdo:,.................,:clllllcccccc::cccclldxxxxdooc;;::cc:;;,,,,;;;;::::cccccllllllllllllllllll
lllllllllllllllllllllllllllllllllllolccol;..';:cloddoolc:::;:cllcc;,,,,,,''''',,,,;::::::c:::ccllolooooooooooddxxddxxxxxddooodkOOkkkkkdodxxoooloolllllllloooooddoollcc::::;;;,',;;'..':odocccllodxkO00OOkxddol,......            ..,;clollllllllcc::ccodxxdddol:;;;:::;,;,,,;;;;;::::cccccllllllllllllllllll
llllllllllllllllllllllllllllloolllooolclol,..,;:cloddolc:::::cllcc:,,,,,''''',,,,',;:::::::ccc:cccclooooddddddddddxxxxxxxxxxdxkOkkkkkkkxdodxxdddxxxddddddddddddxddddddxxxddooc:clc,',:oxxdllooddxkOOOOOOOOOkxl'                     ...,,;;::;;;,,,;:ccloooddol:;;;:c;;,,,,,;;;;;::::cccccllllllllllllllllll
llllllllllllllllllllllooooooooooooooolclodoc,'',;cldddol:::ccclccc:;,,,,'''''',,,',,;;;;::::cccccccllodoodxxxxxxxxkOOOkkkkkxxxxddddxxxkOOkxxxxxddxkxxxxxkkkxdddddddddddxxdxxdolllc::coxxdoloodxxkO0KKK00OOkxdc'.                         ......''',;:ccccclodoc:::cc:;,,,,,,;;;;;::::cccccllllllllllllllllll
lllllllllllllllloooooooooooooooooooooolloxxdl:;,';coddddolccccccc:;;,,'''',,''',,,;;;;;:::::cccccclooodooddxdxxddxkOOOOOOkkxxxxdddxkkxxk0OkkkkxxxxxxxxxxxxxxddddddddoodddddddollooooodxkxoooodkOO000KKKKKK0Odl;,'..                      .    ....',;:cccloddolc::cc;,,,,,,;;;;;:::::cccccllllllllllllllllll
lllllllllllloooooooooooooooooooooooooolcldxxdol:;,;clodddolc::::::;,;,,'',,,''',,;;,,;;;;::::cccclloooooodddoddoodxkkOOOOOkkkOOkxddxxooxkkkkkkkkkkxxxxxxxxxddddddoddoodddxxxdoooddxxxxxxdooooxO00KKKKKXKKK0Oxlcc:;,........   ......   .....     ...';:cccodooooc:cc:;;;;;;;;;;::::::cccccllllllllllllllllll
llllllllooooooooooooooooooooooooooooodolcldxddoolc:;;cllool:,,,;::;,,,,',,'',,'',',,;::;;::::cccccclooloodoollooddxxxxxxxkkkkkkkxxxxdoodxkxxxxxxxdddddddddoooddooooooodddxxxddxxxkkkkxxdollodxkO0KKKKKXKKKKOdlccllool:;,,,''..........',;:;..     ...,;:clodollolccc::;;;;;;::::::::ccccccllllllllllllllllll
lllloooooooooooooooooooooooooooooooodddoccldooddocc:;,,;::::;;,;;;;;,,,',,'',,,,,,,,;:;,;;;;::cc:cclllolooooolloddddddxxkkkkOO0OkkkOOxdoxkOkkkxxddooooooolllloolloddxxkkkkkxxxxkkOOkkkxddolldxkO0KKKKKKKKK0Oxooooddooolccccllc:;,',,:lodolc;,'.. ..';;;::cloolccolllccc::;;:::::::::ccccclllllllllllllllllll
lllooooooooooooooooooooooooooooooooddoddlccooodddlcccc:;::cclc:;,;;;,,,,,,',,,,,,,,',,,,,;::;:::cccccloolooollcllooddxxkkkkkkO00kxxxOOkxxdddxxkxdoooodddoooooddddxkkOOOOOkxxxxxkkO0OOkddoooodxk00KKKKKKKKK0kdddoodddddooooodxxxdddddddxxddoool:,...,:c:;;:ldol:cllolccllcc:::::::::cccccclllllllllllllllllll
ooooooooooooooooooooooooooooooooooddoodddlcclloddocclllllllloolc;,,;,,,,,,,,,,,,,,,,,,,,,,;;;;;;:cccclooooollccclloddddxxxxkkkkkkkxxkkkxxxxxdxkkkxxxxxxxxxxxxxkOOkOOOOkOOOxxdxkkkkkOOOxooooddxkO0KKKKKKKK0Okxxddodxddddooooddxxxxddoooooooooolc::,.,:llccllddoccclllcccccc:::::::::cccccclllllllllllllllllll
ooooooooooooooooooooooooooooooooodddoodddoocclooooolclloooooodol:,,,,,;,,,,,,,,,,,,,,,,,,,;;;;;;::ccclllllllclllllloddddxddxxkkOOOOkxxkkxxxxxxxkOOOkxxkkOOkkkOOOOOkkkxxkkkkkxxkOOkddkOxoooodxxkO0KKKKKKKK0Okxxxddxdoodddooooddxkkxxxdoooooolllllll:;;cooollloolcccclccc:::::::::ccccccccclllllllllllllllllll
ooooooooooooooooooooooooodddddodddooodoodddlcclloodolllooooodddl:;,,,;;;;,,,,,,,,,,,,,,,,;;,;;;;;::::ccclllllllollloddddxxxxkkkkkkOOkkOOOOkxxxxkkOOkkkOOOkkkkkkkkkkkkxxkxxxxxkOOOkdoxkdooooddxO00KKKKKKKK0Okxxxxkkxxdddddddddoodxxxxxxxddooodxxdolcccccloolllccccc:cllcc:::ccc:cccccccccclllllllllllllllllll
ooooooooooooooooddddooodddddddddddooddooooddoc:clooolclooddodddl:;,,,;;,,,,,,,,;;;,,,,,,,,,,,,;;;::::ccllllllllllccloodxxkkkkkkkkkOOOOkkkOkkxxkkOOOOOOOOOkkkkkkkkkOOkkxxkxxxxkOOkxdoxkdddddddxk00KKXXXKKK0Okxxkkkxkkxdoooddddxdddddxxdddddddxkkxdolllcclooolcccccc:cccc:::::::::::ccccccllllllllllllllllllll
oooooooooooooooooooooooooodddddddddddoooddooool:;cllllllooddoolc:;,,,;,,,,,,,,,;;;;,,,,,,,,,,,,,;;:;:::cccccccclllloodddxxxxxkkkOOOOOOOOOOOkkkkOOOkOOOOOOOkkkOOOkkOOkxxxxxxddxkkkxdodxxxddxxkkO00KKXXXXKK0Okkkkkkkxkkkxooloooooddddddddxddxkkkkkdllodooooolc:::::::;:ccc:::::::::::cccccclllllllllllllllllll
ooooooooooooooooooooooooooooooodddoooddoddoooddc,',;:::ccllc:;,;;;,,;;;;;;,,,,,;;;;;,,,,,,,,,,,,;;;;;:ccccc:;:ccllooooddddxxxxxkOkkOOOOOkkOOkkkkOOOOOOOOOOOOOOOOkkkkkkkkkkkkxdxxxxoodxxxkkkOOOO0KKKXXXKKK0OkkkkkkxxxkOkxddooooooooddxxxxkkkkkkkkdlllodddolcc::::;;;;;;::::::::::::ccccccclllllllllllllllllll
oooooooooooooooooooooooodddoooodddoooodddoddoddl;..............';;,,;;;;;;,,,,,,;;;;;;;;;;;,,,,;;;;;;;:::::::ccllllooooooodxxxxxkkkkkkOkkkOOOkkkOOO0OOOOO00000OkkOOOkkOkkkOOkxdddoloodxkkOO00000KKKXXXKKK0OkOkkkkxxkkkOkkkxdoooddoooxxxxxkOOkkkkxddddddolcc::;;:;,,,,,;:;;;;:::::::cccccclllllllllllllllllll
ooooooooooooooooooooodddddddddddddoooododdoooddl;.. .......... .,;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;,;:::ccccclcllllooooodxxxxkkkkkkkkkkkkkOOOOOkkOOOOO00000OOO00OOOOkkxxdddollclodxkOO00K00KKKKXXXKKK00OOkkOkkxkkkkkOOOkxdoolodxxxkkkkxxddxkkOOkxxxolc::,,;;;,,,,,;;;;;;;;:::::cccccclllllllllllllllllll
oooooooooooooooooooooodddddoodddddddoddddooddool;. ........... .,;;;;;;;;;,,,;,,;;;;;;;;;;;;;;;;;;:::;,,;:::::::ccccllloooloddddxkkxxxxxkkkxxkkkkkkkkOOOOOOO00000000OkkkxddddoollcclodxkkO00KKKKKXXXXXKKK000OOOOOkkkkkxxkO0OOOOkxdddddoodxkkkxxxOOOOkkxdlc::;;:;,,,,,;;;,,,;;;;::::cccccclllllllllllllllllll
oooooooooooooooooooooodddddoodddooddodddoooodolc;...............,;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;::::::;;,,;:c:::cclllccllllloooodxxxkxxxxxxxxxkkkkkOOkOOOOOOOOO00OOOOxdddooodoollcccloddxkO00KKKKXXXXXXKKKKKK0OOOOOOOOOkkOO000000Okxxkkxdodddxkkxxkkkkxxdoc;,;;;;;,,,,,,,,,,;;;;;:::cccccclllllllllllllllllll
oooooooooooooooooooooodddddoodddodddooddooodolc;'..............',;;;;;;;;;,;;;;;;;;;;;;;;;;:::;;:c::;;;;,;:ccc:::cc:::clcclooooodddddoodddddxxkkkkOOOOOOO00OOOOOkxddoooooodddoollccloodxkO0000KKXXXXXXXXKKKKK0OOO00000000000000000OkkkOOOkxddxkkxxkOkxdolc:;;;,,;;,',,,,,,,;;;;::::cccccclllllllllllllllllll
oooooooooooooooooooooodddddooddddddoooddooool:;;,.............'',;;,;;;;;;;;;;;,;;;;;;;;;;;;;;;::cc:;;;:;;::::::;;:::cccccllooolooddooloodddxkkkkkOOOOOOOkkkxxddollcllllloxxxdollcclooddxkO000KXXXXXXXXXKKKKK0OOO0000000000000000KK0OOkkkkO0OOOOkxxkkxdoc::;;,,,,,,,,,,,,,,;;;;;:::cccccllllllllllllllllllll
oooooooooooooooooooooodddddddddddddooodddoooc:;;,..........',''',;;,;;;;;;;;;;;,;;:;;;;;;:::;;;::::;;;;;;;:::;;;;;::::::cccclloolloodoooodddxxxxkkkkkxxxxddollccccc::clloddxxdollcclloodxkO0KKKXXXXXXXXXXXXKK00OkkO0000000000000000000OkkkOOOOOOkxdxkxxoc::;,,,,,,,,,,,,,,;;;;;::::cccclllllllllllllllllllll
ooooooooooooooooooooooddddddddddddddddddooool:,,,.........',,,'',;;;;;;;;;;;;;,,,;;::;;;;;::;;:::;;;;;,;;;:::,',;;;,;;;;;:::ccclccccccloddddxxxxxxxddddoollccllool:::cllooodddollccccloddxkO0KKKXXXXXXXXXXXKK0OkkkO0000000000000000000000OkkkkkOOxdddxdolc:;;,,,,;;;,,,;;;;;;;:::::cccccllllllllllllllllllll
oooooooooooooooooooooodddddddddddddddoooooool;'','........',,,'',,;;;;;;;;;:;;,,,;;;::;;;;;:;:::;;;;;,,;;;;:;,',,,,,,;;::;;;;;;;:cclllllooddddddddddooollllodxxxdl:;::ccccclllllllcc::clddxkkO0KKXXXXXXXXXXKK0OOkxxkO0000000000000000000OOkkkxxkkkollddlcc::;;;;;;;;;;;;;;;;;;::::ccccccllllllllllllllllllll
oooooooooooooooooooooooodddddddooooodoooooool;''''..','..',,,''',,;;;;;;;;;;;;;,,;;;;;;;;;;;::::;;;;;,,;:::;,''''.',,,,;;;,,;;::::ccllllllooooooooooollloodxxxdddo:,',;;;;;;::::ccccc:ccloxxxkkO0000KKXXXXXK0OkkkocldkO0000000000000OOOOOOkkxxdxxxo:coolcccc::;;;;:;;;;;;;;:::::::ccccccllllllllllllllllllll
ooooooooooooooooooooooooddddddoooooooooooool:,''','.',;,,',,'''',,,,,;;;;;;;;;;,,;;;;;;;;,,;::c:;,;;,;;;:::;,''...',,,,,,;;;:cllcccclllooolllooolllooooddxxxxdoodoc,..''.......'',;::;;:cloddxkkOOOOO0000000OOkkxo;,:ldkOOOO00OOOOOOOOOOOOkxxxdxxxoc:lolccccc:::::::::::::::::::::cccccllllllllllllllllllllc
ooooooooooooooooooooooooddddddddddoooooooolc;;;;;;,'',,,,'',,''',,,,,;;;;;;;;;;;;;;;;;;,,,,,;:::;;,,,,,;:c:;,,'..',,,,,;;:::::cllllcccclllllcclllloddxxxxxxxdooooooc;......      ....''',;:coodxxxxxkkkkkOOOkkxddo:,';coxkkOOOOOOOOkkkkkkkxxddddddo::lollllcccc:::::::::::::::::::cccccllllllllllllllllllccc
oooooooooooooooooooooooddddddddddoooodddolc:;::;,;;,,,,,,'',,''',,,,,;;;;;;;;;;;;,,;;;;;,;;,,;::::;;;;,,:c:;;,,..'',;;;,,,,,;;:cclllcccccccccclodxxxkkkkkkkxdoooooool:,......       .....',;:loodddddxxxxxxxxdoloooc,,;codxkkkkkkkkxxkkkxxkxdddddol::lollllccccc:::::::::::::::::cccccclllllllllllllllcccccc
oooooooooooooooooooooooddddddddooddooddollllc:;,,;;,,,'',',,,'''',,,,;;;,;;;;;;;;,;;;;;;;;;;;;;;::;;;;;:clc:;,'..'',,;,,',,;;;;::ccc:;;:ccloodxxxxxkkkxkkkkxooooooollll:,'....  ...........',;:clllllllooooolcccooooc;,;:lodxxxxkxxxxxkxxxxxxdddolc:coollllcccccc:::::::::::::::ccccccccllllllllllllccccccc:
oooooooooooooooooooooooooodddoooddoooddoolool:,',::;,,''',,,''''''',,,;;,;;;:;;;;;;;;;;;;;;::::;;::;;;:cloc:;,'..''''',,;:::cccc::;:cclodxxxxdddxxxxxxxxkkkdolooooollllcc::;,'..     .........',,,,,,,;;;;:clodddoool:;;::clodxxxxxdddxxdddddddolcccloollllccccc::::::::::::::::ccccccccllllllllllccccccc:::
ooooooooooooooooooooooooooooooooooooooooooool;'',:c:;,''',,,'''''''',,;;,;;;::;;;;;;;;;;;;::cc:;;;:;;;:clll:;;'..''',,;:clcclc:::ccodddddxxddddddxxxxxxkkkkxolloooooollllc::::;,..       ................,cdxxxddddolc:;:cccllodddddddooddddoolcc:clllllllcccc:::::::::::::::::ccccccccllllllllccccccc:::::;
oooooooooooooooooooooooooooooooooodddoooooodl;'',:c:;,,,,;;,''''''''',;;,;;;::;;;;;;;;;::;;;cll:::::;::clllc:;,..',,,;::ccc:::clloooooddddxxxxddoddxdddxxkxxdollllooolllllc:::;;;,..        .....   ..',;cdxdxxdoooooc:;::ccclllooooooolllooolc::cclllccccc:::::::::::::::::::::cccccccllllllcccccccc:::::;;
ooooooooooooooooooooooooooooooooooooooooooodl;''';:c:,,,,;;,'.'''..'',,,,,;;::;;;;:;;;;::::::cllc::::cclllol:;,''',;;;:clc::clodoooooodddddxxxddoodddddddxxxxdoollloolccllccccc:;,,'..            ..,;:clodxxxxdoooool:;;;:::cccclollllcccclc::::ccccccc:::::;;;;;;;;;;:::::::::ccccccccccccccccccc::::;;;;;
ooooollllloooooooooooooooooooooooooooooodddoc,,,',::;,,,,,;;'.'''..'',,,,,,,;;;;;;;;;;;;:c:::clllc:;:cllllooc;,'',;;;::clcccllooooooolloooodxdddddddddddddddxxddolooollllllllllc;,,,,..        ..',;:::codxxxxxdooooolc::;,;::cccccc:::::;::;;;:::::::::::;;;;;;;;;;;;;;;::::::::ccccccccccccccc:::::;;;;,,,
ooooolllllooooooooooooooooooooooooooooooodd:'';;,,;:;,;;,';:,..''...'',,,,,,;;;,;;;;;;;::::::cclcc:;;cloooooc;,',;;,;:ccc:ccloooollllllllllloooddddooodddddodxxddolooollllllloolc:,,,'..    ..',;::::cllodxxxxxdolloollccc:;,,;;::;;;,,,,,;;;:::::::::;;;;;,,,,,,,,,,;;;;;;::::::::ccccccccccc::::;;;;,,,,''
oooollllllllooooooooooooooooooooooooooooddl'.'::;,;::;;;,',:;'..'....'',,',,,;,,;;;;,,;:c:;;:cc::::;;:looool:;,',;;,;ccc:::llollllccccccccccclllloolllooddooddxxdddollllllllllllcc:;,'.....',;;;;:::clooooodddddolllllllcc:;,'',;;,''''..',;:::::::;;;;;;,,,,,''',,,,,,;;;;;;;::::::::::c:::::::;;;;,,,''''.
oooolllllllllllooooooooooooooooooooooooodl,..'::;,,;;;,;,',::;'.......''''',,,,,,;;;,,,;::;;;cc::::;;:clooolc:,',;;;;cc:::clollccc:;;;;:;,,,;::::cccllooooollodddddddoolllcc:::c:::::;;;;::c:::::cclodddddddddddolllllolllc:,..',,'.....',;:::::::;;;;;;,,,,'''''''',,,,,;;;;;;;:::::::::::::;;;;;,,,''''...
oooollllllllloooooooooooooooooooooooodoc;.. .':c:;,,;,,;;,';::'.........''.'',,,,,;;,,,;;:;;;::;;:::::clooolc:,',;;;;::::cclllc:;,,,''''...'',;;:ccccllooddoooddddddxxxdooddooooooooolloddooooollloodxddxxxdxxxxdollllllllll:'..''.....,;:::::::::;;;;;,,,,''''''''''',,,,,;;;;;;;;;;;::::;;;;;;,,,''''.....
oooollllllllloooooooooooodoooodoooodoc,.......;c:;,;;;,,;,',::;..............'',,,;;,'',;::;;;;,,,;::ccloolcc:,',;,,;:c::cclolc:;,'''...  ...',;;:clc::clodooodddddddxxxdxkxxxxkkkkkxdddddddddoooodxxxxxxxxdddoooollollclcccc,.''...',;:ccc::::::;;;;;;,,,,''''''''''''''',,,,,,;;;;;;;;;;;;,,,,,'''........
ooolllllllllooooooooooooddoddoodddoc,.........':c:;,;;,,;;'';::,...............'',;;,'',;::::;,,,,,;:clloolc::,',;;;;:ccccloddoollc:;'...........',;;;,,;;::ccclloooddddddxxxxxxxkkxxxxxxxxxxxxxxxkkkxxxxxddoollllllllcccccc:,,,''',;:cccccc::::::;;;;;,,,,'''''''''''''''''',,,,,,,;;;;;,,,,,''''..........
ooolllllllloooooooooooodddddddddoc,............,::;',;,,;;,',:c:'................',,,''',;:::;;,,,,,;:loool::;,'';::;;:cclloddddddolc;,,,;;;,'..    ............'',,,;::::clooooddddxxkkxxkkxxxxxxxxxxddxddolc:::cclcccccccc:,,,,,;:ccllcccccc::::::;;;;,,,''''''''''''..'''''''',,,,,,,,,,'''............  
oolllllllllooooooooodddoddddddoc,..............';:;,,;;,,;,'';cc,.................',,''',;:c:;;,,',,;:cloolc::,'',;;;;:clllodddddooooc:::;;;;;:;,'.........     .........''''',;:cclloodddoooooooollllooddool;'.';;:cccccccc:;,,,:ccccllllllcccccc::::;;;,,,,'''''''........'''''''''''''''''...........    
ollllllllllooooooooddddddddddl;'................,::,',;;,,,'',:c:'.................','''',;::;;,,'',;:clolccc:,'';;;:::coooodddddddddolccc;,,;;::::cc::::;;;,,,,,,'................'',;:c:;;;;,,'...',,;:clc;....',,;::::cc;;;;;:cc:coooolllllllcccc::::;;;,,,,''''''............'''''''''............      
llllllllllooooooooddddddddoc;'..'...............':c:,';;,,,,'';::,'.......  ........''''',,,,,,,,''',;clolc::;,',;;;::::coodddxxdoodoollllcc:;;;;;:clooolllloddoodoollc:,'.......................    .............',;::clc:,,;cll::coddoooooollllllcccc:::;;;,,,,,''''..............................        
lllllllllloooodddddddxxdo:'....''.'..............:c:,',;,',;,',;::,..................'''',,;,,,,''''',:lllc:c:,',,,;::::clooodxxxdddollcloool:;,;;;::loooolloddddxxxxxxxxxdollc:,'..................  .......'....',:cccc:;;:clc::coddddoooooooolllllcccc:::;;;;,,,''''..........................           
llllllllllllllloooooddl:'........................;:c;'';;'';;'',:c:,....................'',;;;,,,''',,:cllccc:,',,,;;:cccclloodddxxxdddoooooolc::;;,;::cclllllldddddxxxxkOOkkkkkxxdooollllccccccc:;;,,;::;,,;::;,,;:ccc::;:lllc::cdddddddddddoooooolllllccc:::;;;,,,'''........................             
c::::;,,,,''''''''''''...........................';c:'.,:;'';,'';cc:,.......  ...........'',;;;,,,,',,:ccccc:;''',,,,;:ccllooddddddxxddddooodolc:;;,;;;;;;:clclooodxxdddxxxxxxkkxxkkxdodxxdooolcccccccccccccccclllccllc:cclllccclodddddddddddddoooooollllccc:::;;;,,,'''....................                
................................................ .,cc;.',;'.,;'',:::;,.......     .........',;;,,,''',;clccc:;,',,,,,;;:ccclodddddddxdddoooooooc:;;,,,,,,;;;:::ccloddxdddxkkxxxkkxxxdooddxdddddoooolllcllcccllooooolllcclolccccloooooooodddddddddoooooolllcccc::;;;,,,''..................                  
.........'..... ...................................;c:'.';,'';;'';:::;'.......     .........',;,,'''',;clllc:;,,,,;,,,,;:cllooodddddoooooooolooollc;,,''',,;;;,,;;:ccllloddddddddxxxxdddxxddxxddddocclloolloooddddolcclllllcclloooooooooooooooooooooooolllllccc::;;;,,'''............                       
............  .....................................'::,..,:;'';,',;:::;,.......      .......',;;,,,,,,;cllc::;;;;;;;;,;;:cllloodddoolclllooolllllool:;,'...'','''...''',,,,;;:cclloooooodxxdddlllc:coddooddddddddoc::clolccccllllllllllooooooooooooooooollllccc:::;;,,,''.......                            
.................................................. .,::'.,::,.','',::;;;,'.......     .......',;,,''',;clccll:;;;;;;;:::clooloodddollodoollloooolloolcc:;,,'....................'',,,,,;;;;;;;::::coxkxddddddddooc::lool::::cccccclllllllllloooooooooooolllllccc:::;;,,''.......                            
'.................................................. .;c;'.,c:'.','';:;;:::,.......      ......',,,,''',:lllllc;;;;;:cc::clooodddddddoddddolcllloooloooooc::;;,,'...............    ........,;;:::ldxxxxxxxxxxdol:::lolc;;:c::ccccccccccccllllllloooooooollllllcc:::;;,,''.......                            
''''...............................................  '::,.':c:'.,,,,;::::::;'.......      .....''',,'',:::cllc::;;;:cc:clllloddxxdddddoddxxolllooooooddddollcc:::::::;;;,,,,,,,''.....',,;;;;;;clddxxdxxxxxdool:;clllc:::c::::::::::::cccccclllllllooooollllllccc:::;;,,''......                            
..'''..............................................  .,:;'.,cc;'.,;;;:;;;:::;'.......      . .....'''',;::ccc:;;;,;;;::ccllooddxxddddddodxxxddddoddooooddxddoooolllllllllcccccccccccc:::::::::codddoddxxxdddol::cllc:::::;;;;;;;;;;:::::::ccccclllllooolllllllcccc::;;,,''......                            
....................................................  .;:;'.,cc;'.';:::;,;;::;,........        ....'''',;:clc:;;;;;;;::ccllooodxxdddddxxxxxxxxxxdddddooddxxdooddddxxddoollccclllllccc:ccccccclooodddodxxxdddlcclooc::::;,'',,,,,,,,,;;;;:::::cccllllllllllllllcccc::;;,,''......                            
....................................................   '::;'';cl;..';:::,,,,;;;,........        .....'',;:cccc:;,,;;;::::cllooodddddxxxxxxxxxxkkxdxxxxdddddoodxxxkkkkkkxxddddddoolccccllloooloooddxxddddddolcllol:;;:;,..''''''''''',,,,;;;:::ccccllllllllllllcccc::;;,,''......                            
.....'...............................................  .,::,.':ll:'.';:cc;,',,;;,'.......         ....'',,;;:::;;;;;;;:::ccllloooddddxxxxxxkxxkkkxxxxxxxoooddddxxxxxxddooodddxxxxddoollllloooooddxxkkxddddoccloc:;;;;'............'''',,,;;;:::cccclllllllllllcccc::;;,,,'.......                           
.....'..'............................................   .,:;'.,:lc:,..,:cc:;,',,;;,........         .....'',;;;,,,,,;;;;;:ccllooodddxxxkxxxkkkkkkkkkkkkkxxxxxxxxxxxxkkxxxxxdddddddddooolloooddddxxkxxxxdolclooc;;;;'................''',,,;;:::cccclllllllllllcccc::;;,,,'......                            
....''.',............................................   ..;:;..;c::c;..,;cc:;''',;;,........         .......',,,''',,;,;;:cccllooooddxxxxkkxxxxxxxxkkxxkkkxxxxxxxxxxkkOOOOOOOOOOOOkkkkkxdddxxxxxkkkxxxddoccooc;,,,'.................''',,,;;:::cccclllllllllllcccc::;;,,''......                          ..
....''.''............................................   ..';:,.':c;:c;'.';cc:;''',;;,'........         ......'''.''''',,;:::ccllooooodxxxxkxdddddxxxxkkkkkkxxxxkkkkkkOOOOOkkkOOOOkkkkOOOOOkxxxxkkkkkkkdollll:,,,,'''''''''''''''''''''',,;;;:::ccccllllllllllcccc:::;;,,''......                       .....
....'...'.............................................  ...'::'.,::;;::'.';:::;'''',;,..........           .........''',,;;:::ccllooddddxxxddxxddddxxxxxkkxxxxxkkkkkOOOkOOkkkkkOkkkkkOOOOkkkkkkkkkkxxxdoool;,,,;,,,,,,,,,,,,,,,,,',,,,,,;;;:::ccccllllllllllllcccc::;;,,''......                    ........
.. .''.',............................................    ...':;'';;;,,::,.';;;;,'''',,,...........           .........'',,;;:::clllloddddxxxddddooodddddddxxxxdxxkkOOOOkkkO0OkkkOOkkkOkkkkkkkkkOkkxxdddddl:;;:::;;;;;;;;;;;;;;;;;;;;;;;;;::::cccclllllllllllllccc:::;;,,''......                   ......'',
.  .''.'''...........................................    ....,:,',;;;'';:;'.,;;;,,'.',;,'.........              ........'',,;;:ccccllooodxxxxddoooodooooddddddddxO000OOkkkkOOkkkkkkkkkxxxxkkkkOOOkxddoool:;:cccc::::::::::::::::::::::::::ccccclllllllllllllllccc:::;;,,''......                .......'',,;
.  .'..''......'.....................................     ...';;,',:;,'';:;,'',;;,'''',;,'........                  ......''',;;;;:ccclloddddddollodooooodoooooodxkkkkxxxkkkkxddxxxxxddxxkOOOOOOkxdooooc;'',;;::cccccccccccccccccccccccccccccllllllooollllllllccc::;;,,,''......             .......''',,;;:
.. .''.',......'.......................................   .''..;:;',;;,'',::;'',;;,,,'',,,'.........                 .......'',,,;;;;:cclooooddolllooddooooollllllodddddxxkkkxoooodxdoodxkOOkkkkxddool:'..'''',,;;;;;;;;::cccccccccccllllllllllllloooooolllllcccc::;;;,''.......          ........'',,;;;::c
.. ...',,......'........................................   .,...;:,',;,''',;:;,',,,,,'''',,'.........                   ........',,,,;:::clooooooooloooollooo:;;:ccloooddddxxddddoolloodxxkkkkkxdddol,.......''',,;;;;,,,,,,,;;::ccccllllllooooooooooooooollllccc::;;,,''......         .......'',,;;;::cccl
.. ...',,'.'...'........................................   .;;...;:;,,,;,',,,::;,,''','''','..........                     .........''',,;:cllloooollllccllool:;;;:coooooodooddddolcloddxxxkkkxxddoc'...........'',,;;;;;;,,'''',,,;;;;;;::cccllooooooooolllllcc:::;;,,''......       .......'',,;;:::ccclll
.. ....''.''.........................................       ':,..';:;,,;;,',,,;::;'''',,',,,,'..........                          ......'',;:ccllllllllllclllllc:,',clllloooooooooooooodxxkkkxxddo:...............''',,;;,,,,,,,,,,,,,,,,,,,,,;;;;::cllllllllccc::;;,,''.......     ......''',,;;::ccclllooo
..  ...''.''............................................    .;:'..',;:;,,;,','';::;,'''''''',,'.........                               .....',::::ccccccclccc:;;;,'';:ccclllooooloddddddxxxxdddol;.................''',,,,,,,,,,,,,,,,,,,,,;;;,,,,,,,,;;::ccccc::;;,,'''.......  .......'',,;;;:cccllllooodd
... ..',,..'...'...'....................................    .'::'..',;:;,,,,,,'',;::,..'',,,,,'........                                     ....'',,,,''..'','',,;,,,;::::cllllcclodddddxxdddooc;...................'',,'''''',,,,,,,,,,'',,,;;;;;;,,,''',,,;;;;;;;,,''...............'',,;;::cccllloooddddd
.'.. ..,,'.'...'...'.....................................    .;c;...',;::,',,,',,,,:c:'.',,,,,,,''.....                                          ........ ...'',;:;,'',,,;;;;;:::::looodooool:;,'.....................'''',,''''',,,,,,,,'''',,,,;;;;;,,,''',,,,,;,,,''............''',,;:::ccllllooodddxxxx
.''....','.''..'...'...................'..................    '::;...'';;:;'',,'',;;;c:,.',,,,,''''.......                                                 .............'.....,;;;;::ccllc:;,,,,'......................'''''''',,','''',,,''''''',,;::;;;,,,,''',,,,,,,'.........'',,;;;::clllloooddddxxxxxk
..''...''..''..'...'......................'.................  .,cc;...''',;;,,,,'',;;;::;'.''','''''........                                                                  ...'',,;,,'''',;,;,'''...................',''''''''''''',,,''''''''',,;::::;;;,,,'''''',,,'''....'',,;;::cclllloooddddxxxxkkkk
...''..''..''..''..''.............'......''..................  .:cc;'..','',;,'''',,,,;:c:,..'''''''''.......                                                                   ........',;;;;,;;,,'''............'',,,;,,',,,'...'''''''''''''''''',;;;;;;;;;,,''''''',,,,,''''',;::ccclloooddddxxxxxkkkkkk
...''..''..''.','.',''''................'''................... .;cc:;..''''',;;,''',,,,;:c:,...'''''',,'......                                                                      ..',;;:::;,,,,'''....''''''''',,,,,'',,''.........''''''''''''''''',,,,,,,,,''''''',,,,,,,,''',,;:cllodddddxxxxxkkkkkkkk
....''',,'',,',;,.',''''.................'''..................  .::::,..',,'.';;,''',,,;;:::;'...''''''''.......                                                                 ...'',,,,;;::;,,''''''''''''',,,,''''''''...........''''''''''''''''',,,,,,,,,,''''''',,,;;;;,,'''''',;:ccodxxxxkkkkkkkkOOO
....''',,,,,,',,'.''''''''''................................... .';:::;..',,''',,,,'''',;;:::;,...'''''','.......                                                           ......'''''',,,;;;::;;,''',,,,''',,,,''''''''......'''.....''''''',,,,,'''',,,,,'''''''''''',,;;;;,,'''''''''',,:codxkkkkkkOOOOO
'.....'',,,,,'','..'..'''''''........'..'.....'...'............. .'::::;...,,''',;;,'''',,;;;;;,''''''''''''......                                                        .';;,....'''''',,;;;;;;;;;,,''','''''''',''''''....'''......'''...'',,,'',,,,''',,,,''''''''..'',;;;;;,,'''''''''''',;:coxOOO000Ox
'......'',,,,'','..''''''''''.................................... .,;;;;;..',''''',;;,'',;;;;;;,;;,'.....''''.. ...                                                     ..,;;,.....'''''',,,,;;;,;;::;;,,'''',,,'''',,,,''.....'''......''....''',,,''''''''''''''''''''''',,,,,,,''',,,'''','''..';codl:;,'
,'......',,,,'.''..'...........................''..'.............. .',,,;,'..'''',',;;;'',;;;;;;;;,,'.....'''...                                                        .';;,'. .....''',,,,,,;;:;;;;:::;,'','',,,,''',,,''....''...'''.....'''''',,,,,'''''''''''''''''''',,,'''''..''''''''''''....... .,c
;,'.....',,;;,'''..'...........................'''''.............. ..;;,',,'....',,'',;;,',;;;;;;,,'',,'..........                                                    ..',,;,.  .....'''',;;,,,;;:;;,,;;:c:,',,,,,'',,,,,,''..................'''',,,,'''''''''''''''''''',,,,,''''.................... ....
','......,,,;,,''..''.'..................''..........................';:,''''....',''',,,,,,;;;;;;,''''''''.......                                                  ...',',;.    ......''',,;,,;;;;;;;;;::::;;,''''',,,,'''''.................'''..''',,,,,'''''''''''''''',,,,''''.................. ..   .
....... .',,,',,'.'''...................''...''.......................,::;,'''....',''',,;;;,;;,,,,,'..''''''.....                                          ....    ..',,,,.      ....''''''',,;;;;;::::;;;,,,''''''''',,,,'.......................'''',,,,''''''',,,''''''''''''''........  .. ..   .'..  .
.......  .''''''...'.....................''.''''......................':::;;,'.....',,''',,,;;,,,,;;;,'.'''',,'...                                        ...........',,;;.        .....''''',;:::::;::;;,,'''''',''''''''''''......................''',,,,''''''',,,''''''''''''''''....            ....  .
''''..   ................................''............................,::;;;;,.....',,'''',,;;;;,,;;;,'''''''......    ..                            ...... .......'',;;,.         .....''''',;;::;;;,,,,,''''''''''..''''''.......................''''',''''''',,,,''''''....''''''..               ..    
''.'..   ..................................''..........................';;;:;;;,'.....',''''',;::;,,,,;;,''''.............                           ..............'',;:,.           ....','''',,,,,;;,,,,,,',,,,'',,''''...'''.......................'',,,'''''''''''''''.......'''.                ...    
.''''..  ...............................................................,;;;;;;;,'.....''''''',;;;:;,',;;;;,'...............                      .........    ...'',;:;.             ..'''''..'',,;;:;;;;,,,,;;;;,,,,,,,,'...........................',,,,'''''''''''''''.......''.                 .'.    
.''''..  ...............................................................,;;;;;;;,'.........'''''',;;;,,',;;;,'...............                   ............  ....',;:;.              ....''''..'',;:::;;;;;;,,,,;;;,,',,,''..........................'',,,''....'..'''..........'..                 ..     
....''.  ....  ...................................'''''.....'............;:;,,,,,'..........''''''',,;;,''',,,,'.............                  ....  .............,;;;'                ....'''...'',;;;;;;,,,;,,,,,,,'''''''''...'''....................''''....''''...............                         
....''..  ...   ..................................''''''...''............,;;;,''','...........'''','',,;;;,,,,,,,'............             ......'.......'''....,;;;,,.                 .....''....'',,,',,,,,,''''''''''''''''''',''....................'''......................                          
.....''. ....   .................................'''''''...''.............,,,,,''',,.....'.....'',,,''',,,,,;,,'''..............        ................'''''',,,,,,'...                 ....'''....'''''''''''''''''''''''''''''',,,''...............'''''.......................                          
......'......    ..................................''''....''............',,,,,'''',,'....''......',,,'',,,,,,,,''''''''.....................................',,,,,,.  ..         ..      ....',''...''''''''''''''''''''''''''',,',,,''...............'''........................                          
.............    ..................................'''''...''..'..........,;;;,,,'.',,'....''.......'',,,,,,;,,',,,,''',,'...........''..'............'....',,,,',;,.  ..          .... ........'''...'''''''''''''''''''''''''''''',,,''.........................................                          
.............    ..................................'''.'..','.''..'.......,::;;;,''..','...'''.........',,,,,,;,,,,,,,,'''.......',,'''''''''........',,,,,,'','';c;.  ...          ............''''...'''''''''''''''....''''''''.',,,''''........................................                         
.............    ......''..........................'......','.''...........';:::;,,''.'''....''''''......'',,;:ccc:;,,,'.....,;;,,,,''',''.''''... ..',,,,,,,''';lc.  ....           ...........''''...'''''.............'''''''''.''''''','.......................................                         
.............    .........................................',..''..'.......  ..',;;;;,,'''''..'''''',,'',,;;;;;:cloolccc:;,,,,;;;;::;;,,,,'',,,'......'''''''''';ll,   ....             ..........''''..',,,''............'''''''''..'''''',,'.......................................                        
............     .....'.........''''......................,,..''.'........      ...,;;,,,,,'''''''..',;;,;:ccccccllllllc:,,,,,,,,;;;;,,',,''''''',;;,,,;;;;;,,;:c,.  ......             ......''.'',''..',;;,'.....''.....''',,,,'''''''''''''....................'''''..............                       
..'..''''...     ...''''''''.''''''.''...............'''..,'..'............         ....',;;,'.......',;;;;:cllolcccccc:;,,;,,,,,,;;;,,,,'''',,,,,;::cccc::;,,::'.   .......              .........'''...',;:;'.'..'.......'',,,,''''''''''..''.................'''''''...............                      
........'...      ...'',',,''''''''''''....''.''.....'''..'.................            .......',,''''',;::::cllooolccc:;,,,,,,,,,,,,,,,,,,,'',,,;;:::::;;::;;;'.   ........               .. ...........'',;:;,'..'..''...'''',,'''''','....''''............'''''''''''''..............                    
............       ......','''''''''''''...'..''''''........................                   ...'',''',;cccclllooolll:;;,;,,;;;,'',;;,,,,;,,,,;;;:cccc:::::;,.    ........               ...............',;;:;'''','''..'''''''''''''''......''''..........'''''''''....................                  
............              .....'''''''''......'''''.........................                       .......,;:clloooollc;,,,,,,;;;,;;,,',;;;;;,,,;;;::::::::;;,.   ..........              .................'',,;,''',,,'''''...'''''''...........''''''......',,'''.........................                
............                   .......'''''''''......''......................  .                           ...',;cllool:;;:::;;,,;;;,,;;;:::::;::ccccllllc:;,.   ............              ....................'......'''''....''''..............''''''''.....''',''..........................              
'.''.'.....                            .....'''''.'''........................                                    ....'''',;;;:;;;;;;;;;;::;;;;;;:clllllllc:,..  .............             ....................................'''''................'',,;;,...',,'''.........................''...           
..'..'.....                             ............''.......................                                             ........'',;;;:;;;;;;;:ccloooolc;'................               .....................''''''''.....'''''.................'',,,'''...''''''...............................         
'.''.'....     ...                ..............''''..........................                                                      ........''',,;:ccc::;,'.................               .......................''',,''......................'''....',;;,...,,'''.................................      . 
'.'..'....     ....       .......'..',,,''......'''',''.......................                                                                ..................   .........        .       .......................''''............................''',,'''...''''''...............................     ....
.....'...     .........''''''''''....','........,;;,''.........................                                                                                . ..........         ..      .........................................''''''......'''...',,,'..',,''.....'..........................     ....
'.......      .....',,''.............',,'''......'''','........................                                                                            ...................      ...     .....................................'..................','''''....''''','.............................     ....
'......      .... ..''..........'.....',;,,'.....''''''........................                                                                       ......................  ....   ...     ..................................'''......................'','...',,'................................    .....
'.....      ....    .','..........''''',,;,'......'''','........................                                                                              .............     ...  ...      ...........'.....................''''.............................''''''.............................   ......
.....      ......    ...................',,'....''''............................                                                                            ...............           ...     ...........'''''.........''''......................................'''...............................   ......
'...       .......    .,'.........''''..','.....................................                                                                 ...     ...................         ....      .............''..........''.......................................''''..............................   ......
...       ...''...     .'''''''''''.'....'''....................................                                                                           .     ..........          .....     ............''''''.......'''''.........'''''.......................''...............................   ......
..      .....''....    .''''''''''',,,'''''.....................................                                                                                ...........           ....      ........'''''''''..................................................'...............................   ......
       ......''.....    .',,,'''''''''',,,'.....................................                                                                              ...............        ......     .........'''''',''.............'..............................'....................................   ......
     ........''..'...    .'''..'',,,,,,,,'......................................                                                                           .....   .........         ......     .........'''''''''...............................................................................'..  ......
    .........''..''...    .,,''.'''',,,,,,'.....................................                                                                        ........ ............        ......      ...........'',,''.'''...........................................................................'..  ......
  ......'....''..''''..   ..'''',,,,;;;,,'.......................................                                                                      ........    ...........       .......     ............'''............... .........''...'.................'...........................................
 ....''''....''...''''..   .',''''''',,;;,''..''.................................                                                                       ......     ............      .......     ...........''''''.............     ......'.............'...................................................
...''''''.....'...'''...    .''''',,,,,;;;,'...'.................................                                                                       ....      .............      .......      ...........''''''................  .............................................................'.........
..''''........'..........    .,'''',,,,,,,''.....................................                                                                     ......      ............       ........      ...........'''............................    ...........................................................
'''''........''........'..   .'''.',,,,,,''......................................                                                                     ......    .................     .......      ........................................... .............................................................
'''''........''...'....','.   ..''''',,,'........................................                                                                    .....      ..................   .........      .......................................''...............................................................
'''''......''''..'''...'','.   ..''',,,'.........................................                      .    .                                         ....     .   ..      ...................      ...............'''.....................''''''...........................................................
'''''....'''''''''''...',,,..  ..''''''...........................................                          ..                                                                      ...........      ...............''......................'''''...........................................................
'''''.......''''.'''..'',,,'.   ....''............................................                          .....                                   .                                 .........      .......'...............................''''''..'''....................................................'
'''''.....'''''..'''..',,,,'.   .......................''.........''..............                           ......                                ..                                 .....  ..       .......................................'''....'''...................................................',
.''''......'''''.','..''''''.    ......................'''........''''.............                           .......                              .                                   .........      ........................................'...''''...................................................',;
...'''''''''''''.''''''''''..    ..................................'''.............                             .........                                                              .........       ........................................'''''''...................................................',,
''..'.''.''''''''',,,,,,,'...     .''..............................................                               ..........                                                            ........        .......................................'''''''.............................................'....',,'
.'...''..''''....'''',,,,'...     .''..............................................                                 ............                                                         ........        .......................................''''''''................................................'''.
.'..'''...'......',,,,;;,'...      .''..............................................                                   ...........  ..                                                    .......       ....................'''''................'.'''''...........................................'''..'''.
.....'''.''...'...'',,;;,'....     .................................................                                   ............                                                        .......     ....................'''''''...............'..'...............................................''''''''
.....''''''.......'',,;,'.....      ................................................                                       ........                                                          .....      ....................''''''..............................................................''''''''''',
......,,,,'''.'....'',,,'......     ................................................                                            ..                                                            ....      ....................'''''''................''..........................................''''''''''',;
......',,,'.'.'....',,,,'.....      ................................................                                                                                                          .....     ....................''''''''...............''.....'.....................................''''''',,,;:
......',,''''''.....'''''......     ................................................                                                                    .                                      ....     .....................'''''''.....................''............................'.......'''''.'',,;cl
.......',,''.......'',,'........     ...............................................                                                                   ..                                      ....      ....................'''''''.....................'''.........................'.........'''...',,;:co
)";
    cout << sad;
}